### ISSUE TITLE
Support jump_vm for operations on AKS nodes 

### ISSUE THREAD

**Issue by manoatsas** [sassoftware/viya4-iac-azure#115]
* ~~SSH to AKS cluster nodes timeout~~
* install kubectl on jumpvm
* write kubeconfig output to jumpvm to facilitate connecting and running kubectl commands on AKS cluster

**Comment by thpang** [comment]
Currently we don't plan on opening the nodes up to public ssh access. If this is needed lets review for all providers and create issues for each.

**Comment by andybouts** [comment]
I have the same issue.  
The jumpvm should be a proper bastion host with Docker and kubectl.
- I have forked and PR to install Docker on jumpvm, pending merge.
- jumpvm needs kubetctl 1.18.8 installed.
- jumpvm needs networking to allow kubectl after 'export KUBECONFIG=<..>-kubeconfig.conf' has been run.

**Comment by andybouts** [comment]
As a temporary workaround so that I could connect to the k8s api server, the following command was run using the public IP address of jumpvm, but ideally the bastion would connect to the k8s api server via private networking:
```
$ az aks update -n <my-aks> -g <my-rg> --api-server-authorized-ip-ranges "13...."
 - Running ..

**Comment by hahewlet** [comment]
@andybouts  perhaps have the kubectl version install match the K8s version a customer choose for the deployment. Then they will remain in sync vs needing a code update down the line for kubectl as our baseline moves up.

**Comment by andybouts** [comment]
Agreed @hahewlet, I used the same version that is in the requirements on the main readme: https://github.com/sassoftware/viya4-iac-azure

**Comment by manoatsas** [comment]
When there is a need troubleshoot issues or having to install specific libraries required for products (e.g., GPU), there is a need SSH access to K8s cluster nodes. 

I've changes pushed to this branch - https://github.com/sassoftware/viya4-iac-azure/tree/jump-ssh-cfg that address items 1 & 2 in the list. With Snapcraft there are channels for versions that can match major and minor version, but patch may not be available. 

Up on further research there's a bastion feature available that can replace "jumpvm" module
https://azure.microsoft.com/en-us/services/azure-bastion 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bastion_host

**Comment by thpang** [comment]
Access to the nodes from the ssh box will not be enabled. This is a security risk and the connection to the nodes can be achieved without having it built into the code base, i.e. using Lens and it's helper container. As for the bastion box option, we have stayed away from that option as it was not consistent across all cloud providers and our Jump server is. We are also only installing docker on the Jump VM so that folks can use docker containers for running 3rd party tools. If the customer wishes they can install what they like, but we'll just be installing docker. If there is a need for a conversation on these items please setup a meeting.

**Comment by AWSmith0216** [comment]
Is SSH access to the cluster nodes not already enabled from the jump box? I've been able to access cluster nodes in Azure by copying the private key to the jump box, grab the node IP, and SSH in as 'azureuser' I believe.  Or perhaps I'm misunderstanding the discussion.

**Comment by thpang** [comment]
Azure has it turned on by default, but the other providers do not. The goal is to not have any access from the Jump box into the nodes. Again, the work on the nodes should be through the k8s interface not direct IT like interaction.

**Comment by andybouts** [comment]
I believe SSH access as you described should work as expected.  The specific issue I mentioned is that AKS blocks access to the K8s API server (kubectl) unless you run the command I listed about 5 days ago earlier in this thread -and- install kubectl as mentioned at the top of this thread.  It sounds like there are a few opinions on what can/should be done from the jump/bastion host.

**Comment by manoatsas** [comment]
Yes ssh access just need to be documented for internal use. 

@andybouts if kubectl and API access from jumpvm is needed then the changes here allows that - https://github.com/sassoftware/viya4-iac-azure/tree/jump-ssh-cfg, just need the kubeconfig file.

Granted kubectl access is available remotely, in which case is jumpvm even required?

**Comment by manoatsas** [comment]
Reading through the thread history, is there anything to be done here or can this be closed?

**Comment by thpang** [comment]
This one can be closed. We're not providing ssh access, but will providing a pod that one can deploy to access their nodes on each cloud provider. We only provider docker on the Jump VM. If the user needs other tools they can add them. Again for kubectl they can use docker no other tools.
