### ISSUE TITLE
attribute "max_pod" is required

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-iac-azure#119]
Using the latest main branch, it seems that the max_pods parameters has to be explicitly set (instead of using the default value).
I had to set the max_pods explicitly to 110 for each node_pool.

![image](https://user-images.githubusercontent.com/33486843/110437850-17679680-80b6-11eb-8511-a4c13b393af1.png)

**Comment by thpang** [comment]
Yes it does need to be set. This was one of the breaking changes pushed for the last release. You will need to alter your node pool object lists to include items listed here in the [CONFIG-VARS.md](https://github.com/sassoftware/viya4-iac-azure/blob/main/docs/CONFIG-VARS.md#additional-nodepools) doc.
