### ISSUE TITLE
Using NFSv3 in Azure StorageAccount

### ISSUE THREAD

**Issue by akata72** [sassoftware/viya4-iac-azure#121]
Hi,

Do you have any plans of supporting (beta maybe) simply using NFSv3 in a storageaccount. (Currently in preview). This would potentially be a more attractive option than using a VM ( or NetApp) due to the native Azure features available.
 
Regards
Thomas

**Comment by thpang** [comment]
At this time we don't support alpha/beta items in our setups. Only released or production items. What is the state of NFSv3?

**Comment by Pav-Bahia** [comment]
any update on this now NFS has gone live. general availability

**Comment by riragh** [comment]
At this time adding support for Azure StorageAccount is not a priority but will be investigated in future.
