### ISSUE TITLE
TASK [Setup storage folders] failing for viya4-deployment docker deployment

### ISSUE THREAD

**Issue by DevendraYadav1** [sassoftware/viya4-iac-azure#124]
TASK [Setup storage folders] ***************************************************
task path: /viya4-deployment/playbooks/playbook.yaml:34
failed: [localhost -> jump_server_ip] (item=bin) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "bin", "mode": "0755", "msg": "chgrp failed: failed to look up group nobody", "owner": "nobody", "path": "/mnt/viya-share/sinmon/bin", "size": 4096, "state": "directory", "uid": 65534}
failed: [localhost -> jump_server_ip] (item=homes) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "homes", "mode": "0755", "msg": "chgrp failed: failed to look up group nobody", "owner": "nobody", "path": "/mnt/viya-share/sinmon/homes", "size": 4096, "state": "directory", "uid": 65534}
failed: [localhost -> jump_server_ip] (item=data) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "data", "mode": "0755", "msg": "chgrp failed: failed to look up group nobody", "owner": "nobody", "path": "/mnt/viya-share/sinmon/data", "size": 4096, "state": "directory", "uid": 65534}
failed: [localhost -> jump_server_ip] (item=astores) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "astores", "mode": "0755", "msg": "chgrp failed: failed to look up group nobody", "owner": "nobody", "path": "/mnt/viya-share/sinmon/astores", "size": 4096, "state": "directory", "uid": 65534}

PLAY RECAP *********************************************************************
localhost                  : ok=16   changed=3    unreachable=0    failed=1    skipped=9    rescued=0    ignored=0

**Comment by DevendraYadav1** [comment]
Had to create nobody group on jump  to work

**Comment by thpang** [comment]
The Jump server is ubuntu based and has the group for nobody as `nogroup` You should not need to create this group. Also your mount points are incorrect the `/viya-share` location can no longer have `/mnt` as port of the path as this directory is transient on the Jump/NFS servers.

**Comment by DevendraYadav1** [comment]
I have not explicitly  provided the mount path /mnt , I  have used  all  the defaults  of viya4-deployment

**Comment by DevendraYadav1** [comment]
Sorry my bad for using Wrong Repo

**Comment by thpang** [comment]
The latest version of the deployment code base now sets the variable `JUMP_SVR_RWX_FILESTORE_PATH` to the value `/viya-share` Here is the doc location: https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#jump-server If you're using an older version of the iac-deployment container to run your deployment that may be the issue.
