### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by grtn316** [sassoftware/viya4-iac-azure#126]
Hello,

I have followed the steps in the readme but it seems `terraform plan` is not working on windows.

> C:\Users\david\source\repos\viya4-iac-azure>terraform plan
var.prefix
  A prefix used in the name for all the Azure resources created by this script. The prefix string must start with lowercase letter and contain only alphanumeric characters and hyphen or dash(-), but can not start or end with '-'.

>  Enter a value: sasviya

>var.subscription_id
  Enter a value: ***redacted***

>var.tenant_id
  Enter a value: ***redacted***

>Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider

>Error: Invalid function argument

>  on main.tf line 228, in module "nfs":
 228:   ssh_public_key               = file(var.ssh_public_key)
    |----------------
    | var.ssh_public_key is "~/.ssh/id_rsa.pub"

>Invalid value for "path" parameter: no file exists at
C:\Users\david\.ssh\id_rsa.pub; this function works only with files that are
distributed as part of the configuration source code, so if this file will be
created by a resource in this configuration you must instead obtain this
result from an attribute of that resource.

>Error: Invalid function argument

>  on main.tf line 296, in module "aks":
 296:   aks_cluster_ssh_public_key               = file(var.ssh_public_key)
    |----------------
    | var.ssh_public_key is "~/.ssh/id_rsa.pub"

>Invalid value for "path" parameter: no file exists at
C:\Users\david\.ssh\id_rsa.pub; this function works only with files that are
distributed as part of the configuration source code, so if this file will be
created by a resource in this configuration you must instead obtain this
result from an attribute of that resource.

>Error: failed to execute "files/iac_git_info.sh": fork/exec files/iac_git_info.sh: %1 is not a valid Win32 application.

>  on main.tf line 401, in data "external" "git_hash":
 401: data "external" "git_hash" {

>Error: failed to execute "files/iac_tooling_version.sh": fork/exec files/iac_tooling_version.sh: %1 is not a valid Win32 application.

>  on main.tf line 405, in data "external" "iac_tooling_version":
 405: data "external" "iac_tooling_version" {

**2 requests:**

1. When running local, I'd like to be prompted for the ssh key path instead of it being defaulted. Alternatively, I could pass it as a variable but I am getting an error: _A variable named "'ssh_public_key" was assigned on the command line, but the
root module does not declare a variable of that name. To use this value, add a
"variable" block to the configuration._
2. Is it possible to pass my SSH key as a string instead of referencing a file on my system? When automating a deployment, I prefer not to put my ssh key on the deployment agent.

**Comment by thpang** [comment]
There are no plans for a Windows variant at this time. The code must be run from a linux machine.

**Comment by grtn316** [comment]
@thpang Removing the default value for the SSH Key allows me to enter a windows path of my SSH Key. If users do not use the default ~/.ssh path on linux then a modification will still be required.

Maybe worth documenting.

**Comment by raghudevendra** [comment]
Hi ,

Can you please tell how did you resolve the issue.

Error: failed to execute "files/iac_git_info.sh": fork/exec files/iac_git_info.sh: %1 is not a valid Win32 application.

on main.tf line 401, in data "external" "git_hash":
401: data "external" "git_hash" {

Error: failed to execute "files/iac_tooling_version.sh": fork/exec files/iac_tooling_version.sh: %1 is not a valid Win32 application.

on main.tf line 405, in data "external" "iac_tooling_version":
405: data "external" "iac_tooling_version" {
