### ISSUE TITLE
error during deployment terraform

### ISSUE THREAD

**Issue by esshab** [sassoftware/viya4-iac-azure#130]
Error: Post "https://esshab-aks-06136746.hcp.eastus.azmk8s.io:443/api/v1/namespaces/kube-system/configmaps": dial tcp 52.224.89.254:443: i/o timeout

**Comment by manoatsas** [comment]
This is typical symptom when CIDR values for `cluster_endpoint_public_access_cidrs` is not set correctly. Can you verify your IP is within the CIDR?

**Comment by thpang** [comment]
@esshab please verify your IP and CIDR combination. I'll be closing this issue if you don't provide feedback today. Thanks.

**Comment by thpang** [comment]
closing.
