### ISSUE TITLE
Install pip3 on jump / bastion for running Viya4-ARK

### ISSUE THREAD

**Issue by andybouts** [sassoftware/viya4-iac-azure#135]
The jump / bastion host already has python 3, but is missing pip3.
This is required to run the Viya4-ARK: https://github.com/sassoftware/viya4-ark.
I manually installed for now with:
```# install pip3
sudo apt update
sudo apt install python3-pip

**Comment by manoatsas** [comment]
Given OS version using Snap install, installing all the packages in requirements.txt would do, I'd think.

**Comment by thpang** [comment]
I would continue to use the `apt` tools as Snap does not always have the outcome one desires. As a side note, python3 is not the default python version on the Jump box, 2.7 still is setup as the default. If needed the alternate option needs to be setup to force python3 as the default on this system.

**Comment by andybouts** [comment]
Do I need to do a fork and PR for this to be included ... or are you saying that someone will add using apt like I indicated above?

**Comment by thpang** [comment]
I believe there is already a section in the cloud-init script to add packages it could be added there. Yes as a clone/fork and PR would be appreciated.  Will there be a focus on making python3 the default on the vm once it's active?

**Comment by andybouts** [comment]
I can look at that, I cannot recall offhand if I had to make it the default or if I just ran the commands as `python3 ...`

**Comment by thpang** [comment]
I've done this on Ubuntu before here are the commands:

```
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
```

**Comment by thpang** [comment]
In talking with Norm on this one, the IAC code base will install only docker. That will be the extent of the 3rd party tooling installation on the Jump VM. If folks want to enhance the server on their own, they can.
