### ISSUE TITLE
Error waiting for update of Network Interface - Cannot delete nic

### ISSUE THREAD

**Issue by thpang** [sassoftware/viya4-iac-azure#140]
Error: Error waiting for update of Network Interface "...-jump-nic" (Resource Group "...-rg"): Code="OperationNotAllowed" Message="Operation 'startTenantUpdate' is not allowed on VM 't...-jump-vm' since the VM is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete)." Details=[]

**Comment by thpang** [comment]
Have not been able to reproduce this one. Closing.

**Comment by thpang** [comment]
@rdlaitila has seen this again recently. Opening again to investigate.

**Comment by rdlaitila** [comment]
Here is our occurrence:

```
Error: Error waiting for update of Network Interface "<OMMITED>-jump-nic" (Resource Group "<OMMITED>-rg"): Code="OperationNotAllowed" Message="Operation 'startTenantUpdate' is not allowed on VM '<OMMITED>-jump-vm' since the VM is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete)." Details=[]
```

**viya4-iac-azure ref:** main @ ca4f8095f0773db628421b13fe39c4c68b3c1766
**using example cfg:** examples/sample-input.tfvars
**deploy job:** viya4-iac-azure-run-deploy#241
**destroy job:** viya4-iac-azure-run-destroy#416
