### ISSUE TITLE
feat: (IAC-276) Support for Azure Application Gateway ingress controller

### ISSUE THREAD

**Issue by akata72** [sassoftware/viya4-iac-azure#141]
Are you planning to support Appgw ingress controller in the SAS Viya infra setup? (or any other L7/firewall component).

**Comment by thpang** [comment]
HI @akata72, is there a requirement to support this type of gateway to support the SAS Viya 4 software in the future? Looking to see whos done the research.

**Comment by akata72** [comment]
In our case there is a requirement to use Application Gateway w/WAF when exposing SAS Viya services in the AKS cluster. Using AppGW with AppGW-IngressController (AGIC) would in this scenario be the natural choice. Currently we are trying to make this work with Nginx as the backend due to lackoff support for the other scenario.
