### ISSUE TITLE
build fails because the alpine image fetch does not seem to work

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-iac-azure#155]
Hello

The build of the viya4-iac image fails with :

```sh
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
OK: 220 MiB in 77 packages
The command '/bin/sh -c apk --update --no-cache add git openssh   && curl -sLO https://storage.googleapis.com/kubernetes-release/release/v$KUBECTL_VERSION/bin/linux/amd64/kubectl   && chmod 755 ./kubectl /viya4-iac-azure/docker-entrypoint.sh   && mv ./kubectl /usr/local/bin/kubectl   && chmod g=u -R /etc/passwd /etc/group /viya4-iac-azure   && terraform init /viya4-iac-azure' returned a non-zero code: 6
```
I have tried with the main branch and with the 2.1.2 release. Same error.
Thanks

**Comment by raphaelpoumarede** [comment]
I fixed it by restarting the docker daemon on my jump box. 
I'll let the issue open for review/reference by the dev team but you can close the issue if you want.
thanks

**Comment by thpang** [comment]
If you're building your own docker images to use from the repos you'll periodically want to clean up your Docker env as it does cache files/volumes/images etc which consume your local resources. Here is the link to the docker site on `Pruning` enjoy ;)

https://docs.docker.com/config/pruning/
