### ISSUE TITLE
Az "eastus, eastus2, centralus" does not support AKS 1.18.14

### ISSUE THREAD

**Issue by andybouts** [sassoftware/viya4-iac-azure#157]
The required K8s version is 1.18.14, but this version is no longer supported in the 'eastus, eastus2, or centralus' region in Azure.  The 1.18.14 K8s version was supported in May, 2021.  I was able to build a cluster with the IAC at that time.

See [tfvars](https://github.com/sassoftware/viya4-iac-azure/blob/main/examples/sample-input.tfvars):
```bash
kubernetes_version         = "1.18.14"
```

And here's the Az AKS versions available at the 1.18.xx level:
```bash
anbout@cldlgn01:~/viya4-iac-azure$ az aks get-versions --location eastus | grep 1.18
      "orchestratorVersion": "1.18.17",
          "orchestratorVersion": "1.18.19"
      "orchestratorVersion": "1.18.19",
anbout@cldlgn01:~/viya4-iac-azure$ az aks get-versions --location eastus2 | grep 1.18
      "orchestratorVersion": "1.18.17",
          "orchestratorVersion": "1.18.19"
      "orchestratorVersion": "1.18.19",
anbout@cldlgn01:~/viya4-iac-azure$ az aks get-versions --location centralus | grep 1.18
      "orchestratorVersion": "1.18.17",
          "orchestratorVersion": "1.18.19"
      "orchestratorVersion": "1.18.19",
anbout@cldlgn01:~/viya4-iac-azure$
```

**Comment by thpang** [comment]
This will be updated in our next release where we're bumping versions. Linked to PR #153 addressing this issue. In the interim this can be adjusted from your tfvars file.

**Comment by manoatsas** [comment]
This is will be ever changing and depends on what K8s versions Azure supports in a given location. When K8s patch versions are phased out, users should be directed to update value of `kubernetes_version` in their input tfvars.

See tip - https://github.com/sassoftware/viya4-iac-azure/blob/doc_sp_role/docs/Troubleshooting.md#kubernetes-version-is-not-supported-in-azure-region

**Comment by andybouts** [comment]
Thanks for your help, and I understand your point, but the issue is that we have to make sure that the provider (Azure, AWS, GCP, etc) make available a SAS Viya supported version of K8s.

My original question in the issue was not how to change K8s version, but which version of K8s should I change the IAC parameter to.


From: manoatsas ***@***.***>
Date: Monday, June 7, 2021 at 4:32 PM
To: sassoftware/viya4-iac-azure ***@***.***>
Cc: Andy Bouts ***@***.***>, Author ***@***.***>
Subject: Re: [sassoftware/viya4-iac-azure] Az "eastus, eastus2, centralus" does not support AKS 1.18.14 (#157)

EXTERNAL

This is will be ever changing and depends on what K8s versions Azure supports in a given location. When K8s patch versions are phased out, users should be directed to update value of kubernetes_version in their input tfvars.

See tip - https://github.com/sassoftware/viya4-iac-azure/blob/doc_sp_role/docs/Troubleshooting.md#kubernetes-version-is-not-supported-in-azure-region<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsassoftware%2Fviya4-iac-azure%2Fblob%2Fdoc_sp_role%2Fdocs%2FTroubleshooting.md%23kubernetes-version-is-not-supported-in-azure-region&data=04%7C01%7Candy.bouts%40sas.com%7Cd50b71974a074563d50b08d929f36bfc%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637586947736426359%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vV77O%2F3GJwZf5wWkTyugLJ1T5erJ%2F2yOJLYZvkBYBfw%3D&reserved=0>

**Comment by thpang** [comment]
The providers will never make available _a SAS Viya supported version of K8s_, as you stated above. SAS must make sure they run on the currently supported versions of K8s offered by the providers. Why would you think this to be the case?

If you need to know what the provider currently supports you can run this command:

```bash
az aks get-versions --location eastus --output table
```
**NOTE**: You can change the location as needed.

The official docs from SAS on what versions it supports lives [here](https://go.documentation.sas.com/doc/en/sasadmincdc/v_014/itopssr/n1ika6zxghgsoqn1mq4bck9dx695.htm#n0mhb21pl07ohgn1hj4zsgfeq8hj)

**Comment by andybouts** [comment]
This can be closed since it’s been confirmed it will be a 2-step process: (1) verify the K8s version in the provider and (2) select a supported SAS version of K8s that matches from #1.

As time permits, I will draft a PR that will attempt to make this a little easier for others.

**Comment by manoatsas** [comment]
I understand K8s versions can be challenging and it would be ideal to use the values from sample*.tfvars. It may help to move `kubernetes_version` variable to the required variables section.
 
For Viya4 supported K8s versions, refer to - https://go.documentation.sas.com/doc/en/sasadmincdc/v_014/itopssr/n1ika6zxghgsoqn1mq4bck9dx695.htm#n0mhb21pl07ohgn1hj4zsgfeq8hj
then match that 'minor' version from the provider supported K8s versions and pick the 'patch' version currently supported in your location. 
For Azure see this doc on how patch versions are deprecated - https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#kubernetes-version-support-policy
