### ISSUE TITLE
Issue at nvet_subnet

### ISSUE THREAD

**Issue by henmo09** [sassoftware/viya4-iac-azure#163]
I got this error,
containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="SubnetNotFound" Message="Could not find subnet kube4-aks-subnet in vnet kube4-vnet from resource group kube4-rg of subscription 6bea75b7-34c4-477e-bd72-02c58414d151."
│
│   with module.aks.azurerm_kubernetes_cluster.aks,
│   on modules/azure_aks/main.tf line 2, in resource "azurerm_kubernetes_cluster" "aks":
│    2: resource "azurerm_kubernetes_cluster" "aks" {
│

In file: "modules/azure_aks/variables.tf" i think here is the root of the issue
variable
variable "aks_vnet_subnet_id" {
  default = null
}

**Comment by thpang** [comment]
If you're using the `sample-input.tfvars` and have not defined your own network as outlined in the `sample-input-byo.tfvars` sample file, that value is set [here](https://github.com/sassoftware/viya4-iac-azure/blob/main/variables.tf#L550-L556). There error message is saying that subnet is not found. Can you share your tfvars file?

**Comment by henmo09** [comment]
# ****************  REQUIRED VARIABLES  ****************
# These required variables' values MUST be provided by the User
prefix   = "kube5" # this is a prefix that you assign for the resources to be created
location = "westus2" # e.g., "eastus2"
ssh_public_key = "/root/.ssh/id_rsa.pub" # Name of file with public ssh key for connecting to the VMs
# ****************  REQUIRED VARIABLES  ****************

# !NOTE! - Without specifying your CIDR block access rules, ingress traffic
#          to your cluster will be blocked by default.

# **************  RECOMMENDED  VARIABLES  ***************
default_public_access_cidrs = ["0.0.0.0/32"] # e.g., ["123.45.6.89/32"]
# **************  RECOMMENDED  VARIABLES  ***************

# Tags can be specified matching your tagging strategy.
tags = {} # for example: { "owner|email" = "<you>@<domain>.<com>", "key1" = "value1", "key2" = "value2" }

**Comment by henmo09** [comment]
I think if it left blank it should create a whole virtual network. Should’nt it?
Henry

**Comment by thpang** [comment]
So you are using the minimal sample file and did not set the subnet value. Yes it should create the network. I'll have to look into this. Thx.

**Comment by thpang** [comment]
I used the following sample file : https://github.com/sassoftware/viya4-iac-azure/blob/main/examples/sample-input-defaults.tfvars and only changed the what was needed in that file and had no issues in creating a cluster. You'll have to provide more information. Seems like your following the steps correctly.

**Comment by thpang** [comment]
@henmo09 any updates here? Looking for extra information. Thx.

**Comment by thpang** [comment]
@henmo09 this is probably the issue:
`default_public_access_cidrs = ["0.0.0.0/32"] # e.g., ["123.45.6.89/32"]`
This only allows 1 public ip address to hit your cluster: `0.0.0.0` which I do not believe that's what you intended.
If you're not familiar with CIDR blocks and/or your current network setup you might want consult with someone and choose a more appropriate value.
