### ISSUE TITLE
main.tf line 366, in resource "kubernetes_config_map" "sas_iac_buildinfo":

### ISSUE THREAD

**Issue by henmo09** [sassoftware/viya4-iac-azure#165]
PLease, would really appreciate ur help I am close.

Sorry, just learning as i go, seems like i am almost there.
module.jump[0].azurerm_linux_virtual_machine.vm: Creation complete after 1m49s [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/virtualMachines/kube5-jump-vm]
╷
│ Error: Post "https://kube5-aks-1b02fa42.hcp.westus2.azmk8s.io:443/api/v1/namespaces/kube-system/configmaps": dial tcp 20.69.116.17:443: i/o timeout
│
│   with kubernetes_config_map.sas_iac_buildinfo,
│   on main.tf line 366, in resource "kubernetes_config_map" "sas_iac_buildinfo":
│  366: resource "kubernetes_config_map" "sas_iac_buildinfo" {
│
╵
╷
│ Error: Post "https://kube5-aks-1b02fa42.hcp.westus2.azmk8s.io:443/api/v1/namespaces/kube-system/serviceaccounts": context deadline exceeded
│
│   with module.kubeconfig.kubernetes_service_account.kubernetes_sa[0],
│   on modules/kubeconfig/main.tf line 45, in resource "kubernetes_service_account" "kubernetes_sa":
│   45: resource "kubernetes_service_account" "kubernetes_sa" {
│

**Comment by thpang** [comment]
From what I can tell here, you did not provide a `default_public_access_cidrs` as define [here](https://github.com/sassoftware/viya4-iac-azure/blob/main/examples/sample-input.tfvars#L15-L17) for your network.

**Comment by henmo09** [comment]
Yes
I got it fixed. I put the wrong cidr. Now it looks good.
Any documentation as to how to access the cluster once created?
Henry

**Comment by henmo09** [comment]
I have logged in to the vm created by terraform, how can I get access to the Kubernetes?
HEnry
From: Henry Mora
Sent: Thursday, June 10, 2021 9:15 AM
To: sassoftware/viya4-iac-azure ***@***.***>; sassoftware/viya4-iac-azure ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [sassoftware/viya4-iac-azure] main.tf line 366, in resource "kubernetes_config_map" "sas_iac_buildinfo": (#165)


Yes
I got it fixed. I put the wrong cidr. Now it looks good.
Any documentation as to how to access the cluster once created?
Henry

**Comment by thpang** [comment]
You should have a kube config that was generated. The file is the *.conf file where you ran terraform. The name will be based on your prefix and have a name like <your_prefix>-azure-kubeconfig.conf

You can then run the following:
```
export KUBECONFIG=<terraform_directory_where_you_created_your_cluster>/<your_prefix>-azure-kubeconfig.conf
kubectl cluster-info
```
If this shows info on your cluster your golden.
