### ISSUE TITLE
Sensitive tf outputs causes error

### ISSUE THREAD

**Issue by manoatsas** [sassoftware/viya4-iac-azure#167]
Terraform plan hits an error due to sensitive outputs

```
│ Error: Output refers to sensitive values
│ 
│   on outputs.tf line 90:
│   90: output "cr_admin_password" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true
```

**Comment by thpang** [comment]
We'll be removing the recommendation or optional steps on running `terraform plan` in the future. `terraform apply` outputs what the user may want. The apply does not seem to complain, but will review and add the change.

**Comment by manoatsas** [comment]
`terraform plan` would be of general interest for anyone to preview before provisioning cloud resources, irrespective of what's recommended.
