### ISSUE TITLE
Auto-mount NFS on Jumpserver Restart

### ISSUE THREAD

**Issue by andybouts** [sassoftware/viya4-iac-azure#170]
Upon a recent ssh login to the jump-server, the Ubuntu OS indicated that the VM needed to be restarted.

After performing a `shutdown -r now`, and logging back into the jump-server, a `sudo mount -a` was required to mount the NFS.

Requesting that the IAC project be updated so that the NFS will be automatically mounted upon restart instead of requiring the mount command.  

I currently don't have time to work on a PR for this.

**Comment by thpang** [comment]
The mount point is setup as an `automount`. If you access the location `/viya-share`, the mount then activates. This should not cause any issues with the system. Will test with a system where I've shutdown the jump box and then do a deployment to verify.

**Comment by andybouts** [comment]
Thanks, the location `/viya-share` did not appear for a `df -h` until I ran a `mount -a`

I can provide access to my jump if you need.  I built it on Tues of this week from a fresh clone of the IAC

**Comment by thpang** [comment]
You don't even need to run `mount -a` you can simply `cd` into that directory or manipulate as needed. The os `automounts` the directory whenever activity is needed on the `/viya-share` directory. Closing.

**Comment by andybouts** [comment]
You're correct @thpang , sorry I didn't realize the auto-mount configuration was in place
