### ISSUE TITLE
Azure AKS cluster doesn't scale to 0 with enabled autoscaling

### ISSUE THREAD

**Issue by Skib4** [sassoftware/viya4-iac-azure#177]
I've noticed very strange behaviour of AKS cluster after stop K8s deployment using kustomize transformers 
https://go.documentation.sas.com/doc/en/sasadmincdc/v_011/calchkadm/p17xfmmjjkma1dn1b5dcx3e5ejxq.htm
Autoscaling in AKS cluster is on. My environment version is 2021.1 so I can't use cronjobs. 

After stopping deployment node pools should scale to zero. Unfortunately they don't scale to zero - all the time they are in the same old state. I've thought that I should wait about 2 hours to look how autoscaler scale my environment to zero but node pools were in old state - 1 instead of 0. Scaling is required to cost optimization.

The only way to scale environment to zero is disable autoscaling and scale manual node pools to zero. When I want to scale environment to old state before stopping i scale node pools to 1 and reenable autoscaling. 

There is a code from terraform.tfvars
```
# AKS config
kubernetes_version         = "1.19.11"
default_nodepool_min_nodes = 1
default_nodepool_vm_type   = "Standard_D8s_v4"

# AKS Node Pools config
node_pools = {
  cas = {
    "machine_type" = "Standard_E8s_v3"
    "os_disk_size" = 200
    "min_nodes"    = 0
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=cas:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "cas"
    }
  },
  compute = {
    "machine_type" = "Standard_L8s_v2"
    "os_disk_size" = 200
    "min_nodes"    = 0
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=compute:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class"        = "compute"
      "launcher.sas.com/prepullImage" = "sas-programming-environment"
    }
  },
  connect = {
    "machine_type" = "Standard_E8s_v3"
    "os_disk_size" = 200
    "min_nodes"    = 0
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=connect:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class"        = "connect"
      "launcher.sas.com/prepullImage" = "sas-programming-environment"
    }
  },
  stateless = {
    "machine_type" = "Standard_E8s_v3"
    "os_disk_size" = 200
    "min_nodes"    = 0
    "max_nodes"    = 2
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=stateless:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "stateless"
    }
  },
  stateful = {
    "machine_type" = "Standard_E8s_v3"
    "os_disk_size" = 200
    "min_nodes"    = 0
    "max_nodes"    = 3
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=stateful:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "stateful"
    }
  }
}
```

**Steps to recreate the behavior**
Stop Viya deployment using kustomize transformers ( like in official documentation ).
Autoscaling to 0 doesn't work. 

**Preferred behaviour**
After stopping deployment AKS cluster node pools scale to 0 without manual interaction.

**Comment by thpang** [comment]
So you have to check each node and see if there are system level deployments/pods/etc running on those nodes. Also did you check the autoscaler pod and watch it's logs to see what/why it was/was not able to autoscale? If you can collect more information that would be helpful.

**Comment by thpang** [comment]
@Skib4 any luck on verifying your nodes/pods and the scaling issue?

**Comment by thpang** [comment]
Closing, found this to be working. Asked for more information. No response from customer.
