### ISSUE TITLE
node_pools

### ISSUE THREAD

**Issue by henmo09** [sassoftware/viya4-iac-azure#178]
Node_pool are being created cas,connect, etc but the node count is 0/0 ready any reason why?
default = {
    cas = {
      #"machine_type" = "Standard_E16s_v3"
      "machine_type" = "Standard_DS1_v2"
      "os_disk_size" = 200
      "min_nodes"    = 1
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=cas:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class" = "cas"
      }
    },
    compute = {

      #"machine_type" = "Standard_E16s_v3"
      "machine_type" = "Standard_DS1_v2"
      "os_disk_size" = 200
      "min_nodes"    = 1
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=compute:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class"        = "compute"
        "launcher.sas.com/prepullImage" = "sas-programming-environment"

**Comment by YuryShkoda** [comment]
The same issue.
Terraform apply output:
```
Apply complete! Resources: 31 added, 0 changed, 0 destroyed
```
Azure Portal:
![image](https://user-images.githubusercontent.com/25773492/126164038-f1be84e3-8359-42e6-9093-af4ddaf90768.png)

Deploying Viya4 (https://github.com/sassoftware/viya4-deployment) with tags `baseline,viya,install`, makes no effect on node count.

**Comment by thpang** [comment]
I successfully stood up an Azure cluster this evening and verified that with auto scaling enabled, the node pools did start with their minimal amount:

![image](https://user-images.githubusercontent.com/32514746/126244699-4a228ebc-a137-4144-9d7e-d783597342b6.png)

How long did you wait before looking at these node counts?

**Comment by YuryShkoda** [comment]
> I successfully stood up an Azure cluster this evening and verified that with auto scaling enabled, the node pools did start with their minimal amount:
> 
> ![image](https://user-images.githubusercontent.com/32514746/126244699-4a228ebc-a137-4144-9d7e-d783597342b6.png)
> 
> How long did you wait before looking at these node counts?

for a few hours.

**Comment by YuryShkoda** [comment]
I've managed to resolve this issue by providing `AKS Node Pools config` in `terraform.tfvars`.
Thanks, @thpang for support.

**Comment by henmo09** [comment]
what was the variable you added in tfvars?

**Comment by thpang** [comment]
@henmo09 if needed take a look at these examples and you can see how to setup your tfvars file: https://github.com/sassoftware/viya4-iac-azure/tree/main/examples

**Comment by henmo09** [comment]
min_nodes is the variable set to 1 so it should give me what i expect
default = {
    cas = {
      #"machine_type" = "Standard_E16s_v3"
      "machine_type" = "Standard_DS1_v2"
      "os_disk_size" = 200
      "min_nodes"    = 1
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=cas:NoSchedule"]

**Comment by henmo09** [comment]
![image](https://user-images.githubusercontent.com/85652963/126327058-63402bfe-e5e6-4f80-af8e-f3d497edd24e.png)
[](url)
![Capture](https://user-images.githubusercontent.com/85652963/126327141-f7aa6f1a-56a7-4381-8520-2c8868f095e1.JPG)

**Comment by thpang** [comment]
So you're comment shows you have setup a machine type of:

"machine_type" = "Standard_DS1_v2"

for the CAS node pool; however, the screen shot you're sharing shows that's not the case. I am not sure how you're running the application and/or what you've setup. You did not follow the template when filling in information for this issue so there's very little I have to go on.

If you can provide: 

1. How are you running terraform? cli / docker
2. Version of terraform
3. You .tfvars file
4. Capture the output when your run `terraform apply` and either attach or copy that information here.

**Comment by henmo09** [comment]
or I just copied the screenshot from above, UNder the node count column i have 0/0 except for "system" that is what i wanted to emphasizes. 
what i have for node pools is this vm instance:
 default = {
    cas = {
      #"machine_type" = "Standard_E16s_v3"
      "machine_type" = "Standard_DS1_v2"

**Comment by thpang** [comment]
Please provide the information requested.

**Comment by henmo09** [comment]
TFVARS:
root@henmo:~/latest/viya4-iac-azure# cat terraform.tfvars
# !NOTE! - These are only a subset of CONFIG-VARS.md provided for sample.
# Customize this file to add any variables from 'CONFIG-VARS.md' that you want
# to change their default values.

# ****************  REQUIRED VARIABLES  ****************
# These required variables' values MUST be provided by the User
prefix   = "kube5" # this is a prefix that you assign for the resources to be created
location = "westus2" # e.g., "eastus2"
ssh_public_key = "/root/.ssh/id_rsa.pub" # Name of file with public ssh key for connecting to the VMs
# ****************  REQUIRED VARIABLES  ****************

# !NOTE! - Without specifying your CIDR block access rules, ingress traffic
#          to your cluster will be blocked by default.

# **************  RECOMMENDED  VARIABLES  ***************
default_public_access_cidrs = ["0.0.0.0/0"] # e.g., ["123.45.6.89/32"]
# **************  RECOMMENDED  VARIABLES  ***************

# Tags can be specified matching your tagging strategy.
tags = {} # for example: { "owner|email" = "<you>@<domain>.<com>", "key1" = "value1", "key2" = "value2" }

########################################################################


root@henmo:~/latest/viya4-iac-azure# /root/terraform apply -auto-approve -lock=false
module.resource_group.azurerm_resource_group.azure_rg[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg]
module.nsg.azurerm_network_security_group.nsg[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/networkSecurityGroups/kube5-nsg]
module.vnet.azurerm_virtual_network.vnet[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/virtualNetworks/kube5-vnet]
azurerm_network_security_rule.vm-ssh[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/networkSecurityGroups/kube5-nsg/securityRules/kube5-ssh]
module.vnet.azurerm_subnet.subnet["aks"]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/virtualNetworks/kube5-vnet/subnets/kube5-aks-subnet]
module.vnet.azurerm_subnet.subnet["misc"]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/virtualNetworks/kube5-vnet/subnets/kube5-misc-subnet]
module.nfs[0].azurerm_managed_disk.vm_data_disk[3]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/disks/kube5-nfs-disk04]
module.nfs[0].azurerm_managed_disk.vm_data_disk[2]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/disks/kube5-nfs-disk03]
module.nfs[0].azurerm_managed_disk.vm_data_disk[1]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/disks/kube5-nfs-disk02]
module.nfs[0].azurerm_managed_disk.vm_data_disk[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/disks/kube5-nfs-disk01]
module.nfs[0].azurerm_network_interface.vm_nic: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/networkInterfaces/kube5-nfs-nic]
module.aks.azurerm_kubernetes_cluster.aks: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourcegroups/kube5-rg/providers/Microsoft.ContainerService/managedClusters/kube5-aks]
module.nfs[0].azurerm_network_interface_security_group_association.vm_nic_sg: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/networkInterfaces/kube5-nfs-nic|/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/networkSecurityGroups/kube5-nsg]
module.nfs[0].azurerm_linux_virtual_machine.vm: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/virtualMachines/kube5-nfs-vm]
module.node_pools["cas"].azurerm_kubernetes_cluster_node_pool.autoscale_node_pool[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourcegroups/kube5-rg/providers/Microsoft.ContainerService/managedClusters/kube5-aks/agentPools/cas]
module.node_pools["stateless"].azurerm_kubernetes_cluster_node_pool.autoscale_node_pool[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourcegroups/kube5-rg/providers/Microsoft.ContainerService/managedClusters/kube5-aks/agentPools/stateless]
module.node_pools["compute"].azurerm_kubernetes_cluster_node_pool.autoscale_node_pool[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourcegroups/kube5-rg/providers/Microsoft.ContainerService/managedClusters/kube5-aks/agentPools/compute]
module.node_pools["connect"].azurerm_kubernetes_cluster_node_pool.autoscale_node_pool[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourcegroups/kube5-rg/providers/Microsoft.ContainerService/managedClusters/kube5-aks/agentPools/connect]
module.node_pools["stateful"].azurerm_kubernetes_cluster_node_pool.autoscale_node_pool[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourcegroups/kube5-rg/providers/Microsoft.ContainerService/managedClusters/kube5-aks/agentPools/stateful]
module.nfs[0].azurerm_virtual_machine_data_disk_attachment.vm_data_disk_attach[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/virtualMachines/kube5-nfs-vm/dataDisks/kube5-nfs-disk01]
module.nfs[0].azurerm_virtual_machine_data_disk_attachment.vm_data_disk_attach[1]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/virtualMachines/kube5-nfs-vm/dataDisks/kube5-nfs-disk02]
module.nfs[0].azurerm_virtual_machine_data_disk_attachment.vm_data_disk_attach[3]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/virtualMachines/kube5-nfs-vm/dataDisks/kube5-nfs-disk04]
module.nfs[0].azurerm_virtual_machine_data_disk_attachment.vm_data_disk_attach[2]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/virtualMachines/kube5-nfs-vm/dataDisks/kube5-nfs-disk03]
module.kubeconfig.kubernetes_service_account.kubernetes_sa[0]: Refreshing state... [id=kube-system/kube5-cluster-admin-sa]
module.kubeconfig.kubernetes_cluster_role_binding.kubernetes_crb[0]: Refreshing state... [id=kube5-cluster-admin-crb]
kubernetes_config_map.sas_iac_buildinfo: Refreshing state... [id=kube-system/sas-iac-buildinfo]
module.jump[0].azurerm_public_ip.vm_ip[0]: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/publicIPAddresses/kube5-jump-public_ip]
module.kubeconfig.local_file.kubeconfig: Refreshing state... [id=f5f306c4778862df0ef436cfa2ce8642a6fa172c]
module.jump[0].azurerm_network_interface.vm_nic: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/networkInterfaces/kube5-jump-nic]
module.jump[0].azurerm_network_interface_security_group_association.vm_nic_sg: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/networkInterfaces/kube5-jump-nic|/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Network/networkSecurityGroups/kube5-nsg]
module.jump[0].azurerm_linux_virtual_machine.vm: Refreshing state... [id=/subscriptions/6bea75b7-34c4-477e-bd72-02c58414d151/resourceGroups/kube5-rg/providers/Microsoft.Compute/virtualMachines/kube5-jump-vm]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
################################################

varibles for node pools:
variable node_pools {
  description = "Node pool definitions"
  type = map(object({
    machine_type = string
    os_disk_size = number
    min_nodes    = string
    max_nodes    = string
    max_pods     = string
    node_taints  = list(string)
    node_labels  = map(string)
  }))

  default = {
    cas = {
      #"machine_type" = "Standard_E16s_v3"
      "machine_type" = "Standard_DS1_v2"
      "os_disk_size" = 200
      "min_nodes"    = 1
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=cas:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class" = "cas"
      }
    },
    compute = {

      #"machine_type" = "Standard_E16s_v3"
      "machine_type" = "Standard_DS1_v2"
      "os_disk_size" = 200
      "min_nodes"    = 1
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=compute:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class"        = "compute"
        "launcher.sas.com/prepullImage" = "sas-programming-environment"
      }
    },
    connect = {
      #"machine_type" = "Standard_E16s_v3"
      "machine_type" = "Standard_DS1_v2"
      "os_disk_size" = 200
      "min_nodes"    = 1
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=connect:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class"        = "connect"
        "launcher.sas.com/prepullImage" = "sas-programming-environment"
      }
    },
    stateless = {
      #"machine_type" = "Standard_D16s_v3"
      "machine_type" = "Standard_DS1_v2"
      "os_disk_size" = 200
      "min_nodes"    = 1
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=stateless:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class" = "stateless"
      }
    },
    stateful = {
      #"machine_type" = "Standard_D8s_v3"
      "machine_type" = "Standard_DS1_v2"
      "os_disk_size" = 200
      "min_nodes"    = 1
      "max_nodes"    = 3
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=stateful:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class" = "stateful"
      }
    }
  }
}
![image](https://user-images.githubusercontent.com/85652963/126334531-b0c8e10a-5a63-4f89-bb75-41d1d16ff745.png)

**Comment by thpang** [comment]
Ok, is that's all that's in your tfvars file? Are using the Gitlab companion repos?

**Comment by henmo09** [comment]
what u mean?, I am doing following your intructions in github

**Comment by henmo09** [comment]
thats all what i have in tfvars file

**Comment by henmo09** [comment]
i will destroy it and re run it

**Comment by thpang** [comment]
If your tfvars file is that sparse then the system is using the defaults. Those values are:

```terraform
default = {
    cas = {
      "machine_type" = "Standard_E16s_v3"
      "os_disk_size" = 200
      "min_nodes"    = 0
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=cas:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class" = "cas"
      }
    },
    compute = {
      "machine_type" = "Standard_E16s_v3"
      "os_disk_size" = 200
      "min_nodes"    = 0
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=compute:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class"        = "compute"
        "launcher.sas.com/prepullImage" = "sas-programming-environment"
      }
    },
    connect = {
      "machine_type" = "Standard_E16s_v3"
      "os_disk_size" = 200
      "min_nodes"    = 0
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=connect:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class"        = "connect"
        "launcher.sas.com/prepullImage" = "sas-programming-environment"
      }
    },
    stateless = {
      "machine_type" = "Standard_D16s_v3"
      "os_disk_size" = 200
      "min_nodes"    = 0
      "max_nodes"    = 5
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=stateless:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class" = "stateless"
      }
    },
    stateful = {
      "machine_type" = "Standard_D8s_v3"
      "os_disk_size" = 200
      "min_nodes"    = 0
      "max_nodes"    = 3
      "max_pods"     = 110
      "node_taints"  = ["workload.sas.com/class=stateful:NoSchedule"]
      "node_labels" = {
        "workload.sas.com/class" = "stateful"
      }
    }
  }
}
```

As you can see these node pools all have a `min_nodes` value of 0 (zere) which is what your seeing which is correct.

Again, no issue here, the system is creating what you've requested.
