### ISSUE TITLE
updates to machine names and series Vm's causing issues 

### ISSUE THREAD

**Issue by Pav-Bahia** [sassoftware/viya4-iac-azure#181]
### Terraform Version
1.02

```bash
...
```

### Terraform Variable File
sample-input-minimal.tfvars

```terraform
...
```

### Steps to Reproduce
Due to azure policies i have had to alter some Vm settings. detailed below, this is causing issues. below.
policies prevent VM names longer than 15 Characters and the use of V4 series VM's

### Actual Behavior
╷
│ Error: "resource_group_name" may only contain alphanumeric characters, dash, underscores, parentheses and periods
│
│   with data.azurerm_public_ip.aks_public_ip,
│   on main.tf line 277, in data "azurerm_public_ip" "aks_public_ip":
│  277: data "azurerm_public_ip" "aks_public_ip" {
│
╵
╷
│ Error: Post "https://slazsas-aks-099d0392.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/configmaps": dial tcp 20.54.210.197:443: i/o timeout
│
│   with kubernetes_config_map.sas_iac_buildinfo,
│   on main.tf line 366, in resource "kubernetes_config_map" "sas_iac_buildinfo":
│  366: resource "kubernetes_config_map" "sas_iac_buildinfo" {
│
╵
╷
│ Error: Post "https://slazsas-aks-099d0392.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/serviceaccounts": context deadline exceeded
│
│   with module.kubeconfig.kubernetes_service_account.kubernetes_sa[0],
│   on modules/kubeconfig/main.tf line 45, in resource "kubernetes_service_account" "kubernetes_sa":
│   45: resource "kubernetes_service_account" "kubernetes_sa" {
│
╵
╷
│ Error: Post "https://slazsas-aks-099d0392.hcp.westeurope.azmk8s.io:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings": dial tcp 20.54.210.197:443: i/o timeout
│
│   with module.kubeconfig.kubernetes_cluster_role_binding.kubernetes_crb[0],
│   on modules/kubeconfig/main.tf line 53, in resource "kubernetes_cluster_role_binding" "kubernetes_crb":
│   53: resource "kubernetes_cluster_role_binding" "kubernetes_crb" {

```bash
...
```

### Additional Context

**main.tf in modules azurerm_vm updated to remove the -VM**

resource "azurerm_linux_virtual_machine" "vm" {
  name                         = "${var.name}vm01"
  location                     = var.azure_rg_location
  proximity_placement_group_id = var.proximity_placement_group_id == "" ? null : var.proximity_placement_group_id
  resource_group_name          = var.azure_rg_name
  size                         = var.machine_type
  admin_username               = var.vm_admin
  zone                         = var.vm_zone

**location updated in variable** 

variable "location" {
  description = "The Azure Region to provision all resources in this script"
  default     = "West Europe"

**** the root terrform files the following chnages were made.**

**-jump shortened**
**-nfs shortned****

Maint.tf

module "jump" {
  source            = "./modules/azurerm_vm"

  count             = var.create_jump_vm ? 1 : 0
  name              = "${var.prefix}jmp"
  azure_rg_name     = module.resource_group.name

module "nfs" {
  source                         = "./modules/azurerm_vm"

  count                          = var.storage_type == "standard" ? 1 : 0
  name                           = "${var.prefix}nfs"
  azure_rg_name                  = module.resource_group.name

**Variable.tf was updated to point to the locally gnerated ssh keys**

variable "ssh_public_key" {
  type    = string
  default = "~/.ssh/sas.pub"

****vm machines updated to V3 as we currently do not allow V4 Vnms** 
**"Standard_D8s_v4"**
**set to** 
"Standard_D8s_v3"**

**tfvars file additions using minimum file example**

prefix   = "slazsas" # this is a prefix that you assign for the resources to be created
location = "West Europe" # e.g., "eastus2"
ssh_public_key = "~/.ssh/sas.pub" # Name of file with public ssh key for connecting to the VMs

default_public_access_cidrs = ["20.xx.xx.x/33"] = x placed to secure 

****tags = = again added as per instructions**

**rest left the same in tfvars file until terraform is working****

**Comment by thpang** [comment]
Your CIDR block is incorrect. Should be:
```terraform
default_public_access_cidrs = ["20.xx.xx.xx/32"]
```
Note the /32 not a /33. That's not a valid CIDR mapping.

**Comment by Pav-Bahia** [comment]
sorry typo on my part,
 it is 32  
default_public_access_cidrs = ["20.67.XX.X/32"] # e.g., ["123.45.6.89/32"]
when i added the XX i typed 33 instead of 32 
but the file does contain /32

**Comment by thpang** [comment]
From the machine you're running the repo code run this command:
```bash
curl -s ifconfig.me
```
That value should be the entry you're adding to the cidr block. Please verify

**Comment by Pav-Bahia** [comment]
ok i tried that, CIDR block i was using was CIDR of the VM that i want to run everything from eventually.
but i have update the CIDR block to my current W/S,, but i still get the same errors. 
im using windows 10 WSL at the moment.. i will fire up an ubuntu VM 18.04 and report back.

**Comment by thpang** [comment]
The code base does not support Windows. You'll have to run from a Linux or Mac OS.

**Comment by Pav-Bahia** [comment]
Ok update code base to run on ubuntu and i still get the same error msgs

**Comment by thpang** [comment]
It's a CIDR issue. The entry in your CIDR block must match either the network or the IP of the machine you're accessing the cluster. Also it's complaining about your resource group name in the error you provided did you fix that?

**Comment by Pav-Bahia** [comment]
the cidr block 
default_public_access_cidrs = ["77.99.122.106/32"] # e.g., ["123.45.6.89/32"]

resource group prefix = slazsas

i'll try running it with just = slaz

**Comment by thpang** [comment]
So as long as your machines IP is: `77.99.122.106` things will be fine there. The resource group name looks fine as well. If you saved the file on a Windows machine you may have introduced file format issues. I would start fresh on the Ubuntu box and see how far your get.

**Comment by Pav-Bahia** [comment]
Hi
I have copied fresh files and updated them but still the same issue. 
could the split on line 278 be my issue

data "azurerm_public_ip" "aks_public_ip" {
  name                = split("/", module.aks.cluster_slb_ip_id)[8]
  resource_group_name = "MC_${module.resource_group.name}_${module.aks.name}_${module.resource_group.location}"
  depends_on          = [module.aks, module.node_pools]

i assume its a seperater "/" ??

**Comment by thpang** [comment]
This appears to be the code your referring too:

```terraform
data "azurerm_public_ip" "cluster_public_ip" {
  count               = var.aks_private_cluster ? 0 : 1

  # effective_outbound_ips is a set of strings, that needs to be converted to a list type
  name                = split("/", tolist(azurerm_kubernetes_cluster.aks.network_profile[0].load_balancer_profile[0].effective_outbound_ips)[0])[8]
  resource_group_name = "MC_${var.aks_cluster_rg}_${var.aks_cluster_name}_${var.aks_cluster_location}"

  depends_on = [azurerm_kubernetes_cluster.aks]
}
```
Where this line is throwing the error: 
```terraform
  resource_group_name = "MC_${var.aks_cluster_rg}_${var.aks_cluster_name}_${var.aks_cluster_location}"
```

The error is stating that the variable `${var.aks_cluster_rg}` and/or `${var.aks_cluster_name}` and/or `${var.aks_cluster_location}` are not formed correctly causing the resulting `resource_group_name` to be malformed.

You'll have to determine what items have been created, i.e.

>- Was the AKS resource group created? You'll need to check the Azure portal to determine that.
>- If the cluster was setup what is it's name? Again in the portal you'll need to verify that the AKS cluster was configured
>- You'll have to validate the cluster location. Azure portal again.

In all cases you can verify what's been created up to a given point by using the Azure Portal. Once you're in the portal you can also look to see if the AKS resource groups name is there and has the correct format.

We've not tested the code in the `West Europe` location. There may be an issue there. 

If you can provide information on what you find in more detail that would help.

**Comment by Pav-Bahia** [comment]
OK the Resource group is being created and partially populated. So why the name error i don't know.
i'll do a test in Est US and see if that works.

**Comment by Pav-Bahia** [comment]
Resource group and items created

RG created = MC_slazsas-rg_slazsas-aks_westeurope

NAME	TYPE	LOCATION
0ea0362e-51a0-4b9b-be9c-ee9da7071531	Public IP address	West Europe
aks-agentpool-03150549-nsg	Network security group	West Europe
aks-agentpool-03150549-routetable	Route table	West Europe
aks-cas-03150549-vmss	Virtual machine scale set	West Europe
aks-compute-03150549-vmss	Virtual machine scale set	West Europe
aks-connect-03150549-vmss	Virtual machine scale set	West Europe
aks-stateful-03150549-vmss	Virtual machine scale set	West Europe
aks-stateless-03150549-vmss	Virtual machine scale set	West Europe
aks-system-03150549-vmss	Virtual machine scale set	West Europe
kubernetes	Load balancer	West Europe
slazsas-aks-agentpool	Managed Identity	West Europe

**Comment by Pav-Bahia** [comment]
Hi Found the issue, Name format must be the name not the display name, format i assume in varaiables and tfvars. I updated both.
az account list-locations -o table.
Now i only have the following errors which i assume relate to the CIDR adddres


│ Error: Post "https://slazsas-aks-87cc1f1a.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/configmaps": dial tcp 20.56.246.41:443: i/o timeout
│
│   with kubernetes_config_map.sas_iac_buildinfo,
│   on main.tf line 366, in resource "kubernetes_config_map" "sas_iac_buildinfo":
│  366: resource "kubernetes_config_map" "sas_iac_buildinfo" {
│
╵
╷
│ Error: Post "https://slazsas-aks-87cc1f1a.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/serviceaccounts": context deadline exceeded
│
│   with module.kubeconfig.kubernetes_service_account.kubernetes_sa[0],
│   on modules/kubeconfig/main.tf line 45, in resource "kubernetes_service_account" "kubernetes_sa":
│   45: resource "kubernetes_service_account" "kubernetes_sa" {
│
╵
╷
│ Error: Post "https://slazsas-aks-87cc1f1a.hcp.westeurope.azmk8s.io:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings": dial tcp 20.56.246.41:443: i/o timeout
│
│   with module.kubeconfig.kubernetes_cluster_role_binding.kubernetes_crb[0],
│   on modules/kubeconfig/main.tf line 53, in resource "kubernetes_cluster_role_binding" "kubernetes_crb":
│   53: resource "kubernetes_cluster_role_binding" "kubernetes_crb" {

**Comment by thpang** [comment]
Great, and yes the timeout issues are related to the CIDR issue.

**Comment by Pav-Bahia** [comment]
would 0.0.0.0/32 be acceptable for testing, as the CIDR is the last hurdle and keeps failing

**Comment by thpang** [comment]
What machine are your running the terraform/docker/ansible on? From that machine run the following command:
```bash
curl -s ifconfig.me
```
Take the IP returned there and add that to the CIDR block.

For example, if the IP returned was `10.144.3.23` you would add `"10.144.3.23/32"` to your CIDR block.

**Comment by thpang** [comment]
Closing this issue. You've figured out the name issue.

**Comment by Pav-Bahia** [comment]
just to confirm,, user must have contributor roles on the subscription, with  also identity  contributor role..
as i suspect that is the last issue, i have contributor access on the subscription, but not access to add identities/ users

**Comment by Pav-Bahia** [comment]
i have terraform/docker/jq/kubecttl/ azure cli installed

**Comment by thpang** [comment]
Authentication requirements : https://github.com/sassoftware/viya4-iac-azure/blob/main/docs/user/TerraformAzureAuthentication.md
