### ISSUE TITLE
kubernetes informational

### ISSUE THREAD

**Issue by henmo09** [sassoftware/viya4-iac-azure#182]
Kubernetes was deployed successfully, could please let me know what is this
aks_cluster_node_username = "clusterUser_kubeviya-rg_kubeviya-aks"
**aks_cluster_password = <sensitive>**
aks_host = https://kubeviya-aks-0d57c83b.hcp.eastus2.azmk8s.io:443

What would be the AKS_CLUSTER_PASSWORD???

**Comment by thpang** [comment]
There is no password for your kubernetes cluster. You have to use the kube config file generated to access the cluster.

**Comment by henmo09** [comment]
thank you
