### ISSUE TITLE
PGP timeout error

### ISSUE THREAD

**Issue by warrior88** [sassoftware/viya4-iac-azure#187]
The jump VM's cloud-init script is generating keyserver time-out errors when trying to download a public key from a public GPG server in restrictive lock-down environments. When receiving a public key, gpg connects to TCP port 11371, which is likely blocked by firewalls with restrictive outbound rules.
It is recommended to overwrite this port with HTTP or HTTPS port.

**Comment by thpang** [comment]
You'll have to add the file here public key [here](https://github.com/sassoftware/viya4-iac-azure/blob/main/docs/CONFIG-VARS.md#required-variables). If you need the file needs to be stored on your installation machine.
