### ISSUE TITLE
VIya sas install

### ISSUE THREAD

**Issue by henmo09** [sassoftware/viya4-iac-azure#189]
HI I have successfully deployed kubernetes with the variables below. But then I have ran ansible to install viya sa and it went successfull, however seems like pods are crashing.
https://github.com/sassoftware/viya4-deployment
 ansible-playbook   -e BASE_DIR=$HOME/project/viya4-deployment   -e CONFIG=$HOME/project/viya4-deployment/ansible-vars.yaml   -e TFSTATE=$HOME/project/viya4-iac-azure/terraform.tfstate   -e JUMP_SVR_PRIVATE_KEY=$HOME/.ssh/id_rsa   playbooks/playbook.yaml --tags "baseline,viya,install"

TERRAFORM:
# ****************  REQUIRED VARIABLES  ****************
# These required variables' values MUST be provided by the User
prefix   = "kubeviya" # this is a prefix that you assign for the resources to be created
location = "eastus2" # e.g., "eastus2"
ssh_public_key = "/root/.ssh/id_rsa.pub" # Name of file with public ssh key for connecting to the VMs
# ****************  REQUIRED VARIABLES  ****************

# !NOTE! - Without specifying your CIDR block access rules, ingress traffic
#          to your cluster will be blocked by default.

# **************  RECOMMENDED  VARIABLES  ***************
default_public_access_cidrs = ["0.0.0.0/0"] # e.g., ["123.45.6.89/32"]
# **************  RECOMMENDED  VARIABLES  ***************

# Tags can be specified matching your tagging strategy.
tags = {} # for example: { "owner|email" = "<you>@<domain>.<com>", "key1" = "value1", "key2" = "value2" }

subscription_id = "xxxxxxxxxxxxxxxxxxxxxxxx"
tenant_id = "xxxxxxxxxxxxxxxxxxxx"
default_nodepool_vm_type = "Standard_D8s_v4"

node_pools = {
  cas = {
    "machine_type" = "Standard_E16s_v3"
    "os_disk_size" = 200
    "min_nodes"    = 1
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=cas:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "cas"
    }
  },
  compute = {
    "machine_type" = "Standard_E16s_v3"
    "os_disk_size" = 200
    "min_nodes"    = 1
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=compute:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class"        = "compute"
      "launcher.sas.com/prepullImage" = "sas-programming-environment"
    }
  },
  connect = {
    "machine_type" = "Standard_E16s_v3"
    "os_disk_size" = 200
    "min_nodes"    = 1
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=connect:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class"        = "connect"
      "launcher.sas.com/prepullImage" = "sas-programming-environment"
    }
  },
  stateless = {
    "machine_type" = "Standard_D16s_v3"
    "os_disk_size" = 200
    "min_nodes"    = 1
    "max_nodes"    = 2
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=stateless:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "stateless"
    }
  },
  stateful = {
    "machine_type" = "Standard_D8s_v3"
    "os_disk_size" = 200
    "min_nodes"    = 1
    "max_nodes"    = 3
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=stateful:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "stateful"
    }
  }
}

# Jump Box
create_jump_public_ip = true
jump_vm_admin        = "jumpuser"
jump_vm_machine_type = "Standard_B2s"

# Storage for SAS Viya CAS/Compute
storage_type = "standard"
# required ONLY when storage_type is "standard" to create NFS Server VM
create_nfs_public_ip = false
nfs_vm_admin         = "nfsuser"
nfs_vm_machine_type  = "Standard_DS1_v2"
nfs_raid_disk_size   = 128
nfs_raid_disk_type   = "Standard_LRS"
################################################

**Comment by thpang** [comment]
This is an issue for the viya4-deployment repo. There is almost no information here on what the actual problem is accept you state the pods are crashing. Please open an issue there and provide more information about what pods you're looking for, what is the expected behavior, and what you'd hope to have someone help with.
