### ISSUE TITLE
postgress internal/external

### ISSUE THREAD

**Issue by henmo09** [sassoftware/viya4-iac-azure#190]
this variable:

V4_CFG_POSTGRES_TYPE | Postgres installation type | string |   | true | [internal,external] | viya
what means External:, means that there is a DB outside this deployment , no need to deploy while creating kubernets env.
Internal means, that it will install postgress via terraform? and Viya Ansible will parse the tfstate file to get postgress information?
PLease explain a bit
thank you

**Comment by enderm** [comment]
V4_CFG_POSTGRES_TYPE is not a variable used in this project.
It is used in the [viya4-deployment](https://github.com/sassoftware/viya4-deployment) project. For documentation, see: https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#postgres
The variable is used to indicate whether you want the viya deployment to deploy the internal Crunchy pg database server, or use an external database server.

This project (viya4-iac-azure) allows you to create an Azure postgres server instance, which can be used by the Viya deployment (as "external" database)
Does that help?

**Comment by henmo09** [comment]
JUst clarification:
create_postgres                  = true # set this to "false" when using internal Crunchy Postgres.
if value false, DB is not created correct ?
if so at "Viya deployment" , V4_CFG_POSTGRES_TYPE = should be "internal or external ?

**Comment by thpang** [comment]
This belongs in the viya4-deployment repo. The answer to your question is [here](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#postgres). If you set `V4_CFG_POSTGRES_TYPE` to `internal` the Crunchy database needs to be setup inside your cluster. If you set `V4_CFG_POSTGRES_TYPE` to `external` You'll either have to provide a valid tfstate file to process or include [these variables](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#external-postgres).

**Comment by henmo09** [comment]
ok understood, then "Crunchy database needs to be setup inside your cluster" will this be crunchy db will be created by using this variable "create_postgres = false" but i di not see any database created. thats why i got confused.

**Comment by thpang** [comment]
When you're working on the infrastructure side, creating the database is provisioned with the help of your provider. When you are not creating a database, the database is stood up as a deployment or more recently controlled by the Data Server Operator to stand up a db in the cluster. Have you read the documentation for [SAS Viya 4](https://go.documentation.sas.com/doc/en/sasadmincdc/v_016/sasadminwlcm/home.htm) and what's needed to configure and deploy your software? If not that's your best place to start.
