### ISSUE TITLE
Internal Load Balancer

### ISSUE THREAD

**Issue by warrior88** [sassoftware/viya4-iac-azure#201]
This is an enhancement request.

By default, the public AKS cluster creates an external load balancer. However, for the use case when the application is serving internal users and not exposed to internet, an internal load balancer needs to be provisioned. Furthermore, to ensure proper DNS resolution, a static private IP address is required to be assigned to the load balancer.

1. The ansible variable file should allow this feature to be enabled and a static private IP address to be specified.

2. The static private IP address is assigned to loadBalancerIP in the INGRESS_NGINX_CONFIG block in viya4-deployment/roles/baseline/defaults/main.yaml:
INGRESS_NGINX_CONFIG:
  controller:
    service:
      externalTrafficPolicy: Local
      sessionAffinity: None
      loadBalancerSourceRanges: "{{ LOADBALANCER_SOURCE_RANGES |default(['0.0.0.0/0'], -1) }}"
      **_loadBalancerIP: `static private IP`_**

@add-label: enhancement

**Comment by enderm** [comment]
Please have a look at https://github.com/sassoftware/viya4-deployment/pull/148
I believe that change brings you closer to what you need to do. If there are additional features you'd like in addition that what that change provides, please open an Issue on the viya4-deployment project.
