### ISSUE TITLE
How to provision GPU-enabled node pools for CAS?

### ISSUE THREAD

**Issue by pulungw** [sassoftware/viya4-iac-azure#208]
Hi, we want to try running model training on GPU-enabled node in Viya 4. The official [system requirements](https://go.documentation.sas.com/doc/en/itopscdc/v_019/itopssr/n0ampbltwqgkjkn1j3qogztsbbu0.htm#n0w5fc65t90xygn1144r5yhra1l9) doesn't give much info on how to deploy. Do we have instructions on how to provision and deploy Viya 4 with GPU-enabled node pools using viya4-iac-azure and viya4-deployment tools?

I was thinking of changing the cas->"machine_type" in the terraform.tfvars to a GPU-enabled VM, and run the deployment tools, would this be enough? Or is this simply not supported by these tools at the moment? 

The ideal scenario is if we can simply add GPU-enabled CAS worker to an existing cluster only when it is needed, and remove them after use. But I can redeploy the cluster if necessary.

**Comment by thpang** [comment]
You can use a machine type that has the GPU available; however, unless the provider explicitly states the GPU is active you'll have to create a daemon set or other mechanism to load up the GPU libraries to activate those on each node. Currently there is no official mechanism that supports this via the IAC/Deployment tool repos.

As for different machine types / node pool, that's counter to the function of a node pool. [A node pool is a group of nodes within a cluster that all have the same configuration](https://cloud.google.com/kubernetes-engine/docs/concepts/node-pools#overview). That way the cloud provider can stand up n number of nodes in a node pool and know it's always performing the tasks on the same node type.

**Comment by pulungw** [comment]
Thanks for the answer. Looks like there is no simple way to enable GPU yet. We'll try looking for the manual way but I wouldn't know how to start creating a daemon set...

Even if we can activate GPU for CAS node pool, I understand that we can only go GPU all the way, or none at all. I was hoping to get more flexibility with cloud provisioning, but if that's the way it is, then we'll have to do. Thanks again.
