### ISSUE TITLE
Error in permissions when setting up the service principle and running the docker container

### ISSUE THREAD

**Issue by paige-pratt** [sassoftware/viya4-iac-azure#216]
### Terraform Version Details

We are using what is included in the docker container provided by the IaC

```terraform
### Terraform Variable File Details

# !NOTE! - These are only a subset of CONFIG-VARS.md provided as examples.
# Customize this file to add any variables from 'CONFIG-VARS.md' whose default
# values you want to change.

# ****************  REQUIRED VARIABLES  ****************
# These required variables' values MUST be provided by the User
prefix   = "buds" # this is a prefix that you assign for the resources to be created
location = "eastus" # e.g., "eastus2"
# ****************  REQUIRED VARIABLES  ****************

# !NOTE! - Without specifying your CIDR block access rules, ingress traffic
#          to your cluster will be blocked by default.

# **************  RECOMMENDED  VARIABLES  ***************
default_public_access_cidrs = [] # e.g., ["123.45.6.89/32"]
ssh_public_key              = "~/.ssh/id_rsa.pub"
# **************  RECOMMENDED  VARIABLES  ***************

# Tags can be specified matching your tagging strategy.
tags = {"key1" = "buds"} # for example: { "owner|email" = "<you>@<domain>.<com>", "key1" = "value1", "key2" = "value2" }

# Postgres config - By having this entry a database server is created. If you do not
#                   need an external database server remove the 'postgres_servers'
#                   block below.
#postgres_servers = {
#  default = {},
#}

# Azure Container Registry config
create_container_registry           = false
container_registry_sku              = "Standard"
container_registry_admin_enabled    = false

# AKS config
kubernetes_version         = "1.21"
default_nodepool_min_nodes = 1
default_nodepool_vm_type   = "Standard_D8s_v4"

# AKS Node Pools config
node_pools = {
  cas = {
    "machine_type" = "Standard_E16ds_v4"
    "os_disk_size" = 500
    "min_nodes"    = 3
    "max_nodes"    = 3
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=cas:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "cas"
    }
  },
  compute = {
    "machine_type" = "Standard_E32ds_v4"
    "os_disk_size" = 500
    "min_nodes"    = 1
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=compute:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class"        = "compute"
      "launcher.sas.com/prepullImage" = "sas-programming-environment"
    }
  },
  connect = {
    "machine_type" = "Standard_E2ds_v4"
    "os_disk_size" = 500
    "min_nodes"    = 1
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=connect:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class"        = "connect"
      "launcher.sas.com/prepullImage" = "sas-programming-environment"
    }
  },
  stateless = {
    "machine_type" = "Standard_E8s_v4"
    "os_disk_size" = 200
    "min_nodes"    = 1
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=stateless:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "stateless"
    }
  },
  stateful = {
    "machine_type" = "Standard_E8s_v4"
    "os_disk_size" = 200
    "min_nodes"    = 1
    "max_nodes"    = 1
    "max_pods"     = 110
    "node_taints"  = ["workload.sas.com/class=stateful:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "stateful"
    }
  }
}

# Jump Box
create_jump_public_ip = true
jump_vm_admin         = "jumpuser"

# Storage for Viya Compute Services
# Supported storage_type values
#    "standard" - Custom managed NFS Server VM and disks
#    "ha"     - Azure NetApp Files managed service
storage_type = "ha"
# required ONLY when storage_type = ha for Azure NetApp Files service
netapp_service_level = "Premium"
netapp_size_in_tb    = 4

# Azure Monitor
create_aks_azure_monitor = false
```

### Steps to Reproduce

Running the first terraform commands with docker in the Using Docker Container section when using the TF_VAR_use_msi=true, option. OR Running the setup for client secret and client id in Azure Help topics.

### Expected Behavior

We expect to see the preview of the cloud resources when running the docker commands. OR we expect to create a client secret.

### Actual Behavior

After setting the TF_VAR_tenant_id, the TF_VAR_subscription_id, and the TF_VAR_use_msi=true in the azure creds file we ran the docker preview and received this result: 

root@IAC-JumpServer:/viya4-iac-azure# docker run --rm --group-add root \
> --user "$(id -u):$(id -g)" \
> --env-file=$HOME/.azure_docker_creds.env \
> --volume=$HOME/.ssh:/root/.ssh \
> --volume=$(pwd):/workspace \
> viya4-iac-azure \
> plan -var-file=/workspace/terraform.tfvars \
> -state=/workspace/terraform.tfstate
╷
│ Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/257121c7-b5b9-4a6b-9f74-91bd57f1ba04/providers?api-version=2016-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F
│
│ with provider["registry.terraform.io/hashicorp/azurerm"],
│ on main.tf line 6, in provider "azurerm":
│ 6: provider "azurerm" {
│

When this had an issue we tried setting up the client secret and id with the steps in Azure Help Topics to set up the variables  TF_VAR_client_secret and TF_VAR_client_id through the azure cli we get an error with permissions. The error is:

root@IAC-JumpServer:/viya4-iac-azure# TF_VAR_client_secret=$(az ad sp create-for-rbac --role "Contributor" --scopes="/subscriptions/$TF_VAR_subscription_id" --name http://$USER --query password --output tsv)
echo $TF_VAR_client_id
echo $TF_VAR_client_secret
Found an existing application instance of "7652b52c-7c53-41ba-ae4e-f0f0c2aa0b8d". We will patch it
Insufficient privileges to complete the operation.
root@IAC-JumpServer:/viya4-iac-azure# TF_VAR_client_id=$(az ad sp show --id http://$USER --query appId --output tsv)
root@IAC-JumpServer:/viya4-iac-azure#
root@IAC-JumpServer:/viya4-iac-azure# echo $TF_VAR_client_id
7652b52c-7c53-41ba-ae4e-f0f0c2aa0b8d
root@IAC-JumpServer:/viya4-iac-azure# echo $TF_VAR_client_secret

### Additional Context

We are trying to run this in our own azure subscription through SAS. We have ownership of the instance and the subscription so we are unsure why permissions is an issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riragh** [comment]
@paige-pratt Are you still seeing this issue?

**Comment by paige-pratt** [comment]
No, I am not sure how we fixed it back then, but we haven't seen that error since and we have done a number of installations afterwards.

**Comment by riragh** [comment]
Thanks for the update. Closing this issue.
