### ISSUE TITLE
(IAC-421) Fix: tflint issue with default_nodepool_vm_type value

### ISSUE THREAD

**Issue by dhoucgitter** [sassoftware/viya4-iac-azure#222]
### Terraform Version Details

Terraform v1.0.0

### Terraform Variable File Details

variables.tf
────────────────────────────────────────────────────────────────────────────────────────────

variable "default_nodepool_vm_type" {
  default = "Standard_D8s_v4
}

### Steps to Reproduce

Run tflint, a Terraform source file linting tool from the command line in the root level folder of the cloned viya4-iac-azure repository.

Sample output:
❯ tflint
1 issue(s) found:

Error: "Standard_D8s_v4" is an invalid value as vm_size (azurerm_kubernetes_cluster_default_node_pool_invalid_vm_size)

  on main.tf line 145:
 145:   aks_cluster_node_vm_size                 = var.default_nodepool_vm_type

Callers:
   main.tf:145,46-74
   modules/azure_aks/main.tf:50,29-57

Reference: https://github.com/terraform-linters/tflint-ruleset-azurerm/blob/v0.14.0/docs/rules/azurerm_kubernetes_cluster_default_node_pool_invalid_vm_size.md

### Expected Behavior

No output from tflint would indicate no errors found and is the expected behavior.

### Actual Behavior

❯ tflint
1 issue(s) found:

Error: "Standard_D8s_v4" is an invalid value as vm_size (azurerm_kubernetes_cluster_default_node_pool_invalid_vm_size)

  on main.tf line 145:
 145:   aks_cluster_node_vm_size                 = var.default_nodepool_vm_type

Callers:
   main.tf:145,46-74
   modules/azure_aks/main.tf:50,29-57

Reference: https://github.com/terraform-linters/tflint-ruleset-azurerm/blob/v0.14.0/docs/rules/azurerm_kubernetes_cluster_default_node_pool_invalid_vm_size.md

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thpang** [comment]
This is not an error, but a lack of the lint tool knowing about the newer versions of the VM types. If there is an error its on TFLint and should be opened there.

**Comment by dhoucgitter** [comment]
> This is not an error, but a lack of the lint tool knowing about the newer versions of the VM types. If there is an error its on TFLint and should be opened there.

Thanks Thomas, I'll look into doing that then.

**Comment by dhoucgitter** [comment]
Looked into this further, it appears that the enum list that TFLint uses to validate the available vm_sizes is no longer being updated by the compute API team -> https://github.com/Azure/azure-rest-api-specs/issues/10033#issuecomment-657701452
I'll look into whether or not this particular warning can be ignored for now since it is a false indication that something is wrong given the situation.

**Comment by thpang** [comment]
Strange as I see Standard_D8s_v4 in the valid list on the main and v0.14.0 branch

**Comment by dhoucgitter** [comment]
> Strange as I see Standard_D8s_v4 in the valid list on the main and v0.14.0 branch

This is the v0.14.0 ruleset I referenced, it doesn't seem to have the Standard_D8s_v4 entry in that list https://github.com/terraform-linters/tflint-ruleset-azurerm/blob/v0.14.0/docs/rules/azurerm_kubernetes_cluster_default_node_pool_invalid_vm_size.md
Can you link me to the list that you are seeing it in?

**Comment by thpang** [comment]
Was this issue not address with this PR #223 ?

**Comment by thpang** [comment]
Nope you should have linked the issue with the PR. That way when the PR is closed, if it covers all aspects of an issue, then the associated issue is also closed. Just a learning moment ;)

**Comment by dhoucgitter** [comment]
OK, thanks @thpang, I think I've got it linked now.
