### ISSUE TITLE
Postgres 12 not supported

### ISSUE THREAD

**Issue by mauriziopinzi** [sassoftware/viya4-iac-azure#230]
I tried to use this block

postgres_servers = {
  default = {
    sku_name                     = "GP_Gen5_4"
    storage_mb                   = 51200
    backup_retention_days        = 7
    geo_redundant_backup_enabled = false
    administrator_login          = "pgadmin"
    server_version               = "12"
    ssl_enforcement_enabled      = true   
  }
}

but I got

│ Error: expected version to be one of [9.5 9.6 11 10 10.0], got 12
│
│   with module.postgresql["default"].azurerm_postgresql_server.server,
│   on .terraform/modules/postgresql/main.tf line 1, in resource "azurerm_postgresql_server" "server":
│    1: resource "azurerm_postgresql_server" "server" {

As Postgres 12 is supported by VIYA could you please add it?

**Comment by thpang** [comment]
Azure does not support version 12 at this time : https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions
