### ISSUE TITLE
NFS mount fails when setting netapp_protocol to NFSv4.1

### ISSUE THREAD

**Issue by jeread** [sassoftware/viya4-iac-azure#236]
### Terraform Version Details

{
  "terraform_version": "\"1.1.4\"",
  "terraform_revision": "null",
  "terraform_outdated": "true",
  "provider_selections": "{\"registry.terraform.io/hashicorp/azuread\":\"1.5.0\",\"registry.terraform.io/hashicorp/azurerm\":\"2.62.0\",\"registry.terraform.io/hashicorp/cloudinit\":\"2.2.0\",\"registry.terraform.io/hashicorp/external\":\"2.1.0\",\"registry.terraform.io/hashicorp/kubernetes\":\"2.3.1\",\"registry.terraform.io/hashicorp/local\":\"2.1.0\",\"registry.terraform.io/hashicorp/null\":\"3.1.0\",\"registry.terraform.io/hashicorp/template\":\"2.2.0\",\"registry.terraform.io/hashicorp/tls\":\"3.1.0\"}"
}

### Terraform Variable File Details

storage_type = "ha"
netapp_service_level = "Premium"
netapp_protocols = ["NFSv4.1"]

### Steps to Reproduce

Set netapp_protocols to NFSv4.1

### Expected Behavior

Jumpbox successfully mounts the NFS share.

### Actual Behavior

Fails to mount NFS share.  Running the mount command from the command line give a permission denied error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riragh** [comment]
Changes were added in PR #325, not sure why this didn't close automatically. Closing this issue now.
