### ISSUE TITLE
feat: (IAC-1322) Private Endpoint for Azure ACR when the Cluster has cluster_api_mode = "private"

### ISSUE THREAD

**Issue by nachai9** [sassoftware/viya4-iac-azure#243]
Typically when the Kubernetes Cluster has cluster_api_mode = "private" mode, Private Endpoint is created for KUBEAPI Server. Similarly if we can create one more Private Endpoint for Azure ACR that will help us to talk to ACR over Private Network instead of going on Public Internet. Also most customers don't want to get on Public Internet when the cluster is Private and wants to avoid tweaking egress traffic and firewall rules just for ACR.

**Comment by nachai9** [comment]
One thing to remember is that if we need Private Endpoint for ACR, we need to use Premium SKU for ACR.

**Comment by riragh** [comment]
Internal enhancement ticket was opened for this request.

**Comment by riragh** [comment]
After PM review the internal request ticket was closed as this nice to have but does not have any immediate requirement. User can manage creating private endpoints for ACR external to IAC. Closing this issue based on review.
