### ISSUE TITLE
Support zone redundant ACR

### ISSUE THREAD

**Issue by nbattala** [sassoftware/viya4-iac-azure#283]
Hi, Thank you very much for making this project available to public! This project has sped up and streamlined our Viya4 deployments and has saved us a tons of time.

Currently the ACR gets created with zone redundancy disabled. It would help us and I am sure the community to have an option of enabling zone redundancy for ACR for high availability purposes. 

Thank you again for all you are doing to help the SAS community!
Naveen

**Comment by riragh** [comment]
After PM review the request was closed as this can be managed by user external to IAC. Closing this issue based on PM review.
