### ISSUE TITLE
Feature Request: Ability to specify the private DNS zone resource id for private AKS cluster

### ISSUE THREAD

**Issue by morenovj** [sassoftware/viya4-iac-azure#298]
Hi,

I am opening this issue to request the possibility of specifying through a terraform variable the private DNS zone resource id to use for new AKS private cluster deployments. 

**Actual Situation**

When the AKS cluster is set to be in private mode and the networks provided in a BYO networks schema have a custom DNS linked, this can cause errors during the deployment of the cluster because the Kubernetes agents are not able to resolve the cluster endpoint. This situation is documented in the following link from official MS doc:

[AKS - Private clusters with hub and spoke with custom DNS](https://learn.microsoft.com/en-us/azure/aks/private-clusters#hub-and-spoke-with-custom-dns)

**Additional information**

After the research done, the understanding is that this private dns zone resource id can be specified through the [private_dns_zone_id](https://registry.terraform.io/modules/Azure/aks/azurerm/latest#input_private_dns_zone_id) variable in the AKS module.

**Desired Outcome**

Have the possibility to specify in the terraform variables file (.tfvars) with an optional variable the AKS private DNS zone resource id to be used. For example:

_aks_private_cluster_private_dns_zone_value = "/subscriptions/<subscriptionID>/resourceGroups/<resourceGroupName>/providers/Microsoft.Network/privateDnsZones/privatelink.eastus.azmk8s.io"_

**Reference PR: #297**

**Comment by riragh** [comment]
Changes were merged to staging, and will be available in the upcoming release.
