### ISSUE TITLE
feat: (IAC-1324) Define additional variable for jump_os_disk

### ISSUE THREAD

**Issue by Ben-42** [sassoftware/viya4-iac-azure#313]
### Terraform Version Details

1.3.9

### Terraform Variable File Details

customized tfvars file / vms.tf

### Steps to Reproduce

If you run the script and add a local mirror registry for your cloud vendor, you probably want to use the SAS mirror manager cli on the jumphost to push the Viya container into your local registry.
The mirror manager needs a temp folder on the local disk of the jumphost but the 64 GB OS Disk is too small for the cache folder of the mirror manager. 

If you run the mirror manager and you don't add an additional disk or resize the disk the container sync fails with "no space left on device"

Of course you can add a data disk to the jumphost afterwards or resize the disk but it would be good to save this additional effort. 

### Expected Behavior

A possibility to add a variable in the tfvars file like jump_vm_os_disk_size for getting a disk with more space for the mirror manager.

### Actual Behavior

You will get an error if you try to sync the container in the local registry with "no disk space left" because you can't change the OS disk size of the jumphost. 

### Additional Context

We try to build a CI/CD Pipeline and the pipeline clones the repo with every run. This additional variable would make it easier to build the pipeline also for others. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riragh** [comment]
An internal ticket IAC-1324 has been created to investigate this request further.

**Comment by riragh** [comment]
This request was reviewed in internal meeting and based on discussion it was determined that Jump server isn't intended to be used for testing or adding data. Jump server is only intended to be an entry point for NFS or other minimal operations. 
User can modify the code on their end and continue using Jump server for their use case. No changes on IAC as this is as designed.
