### ISSUE TITLE
fix: (IAC-1321) NSG gets created in AKS resource group instead of Network Resource Group

### ISSUE THREAD

**Issue by st-jan** [sassoftware/viya4-iac-azure#328]
### Terraform Version Details

Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.38.0
+ provider registry.terraform.io/hashicorp/azurerm v3.54.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

### Steps to Reproduce

Run the IaC script without supplying an NSG name in the terraform.tfvars. i.e. let the IaC create the NSG itself.

### Expected Behavior

The NSG should be created in the network resource group.

### Actual Behavior

The NSG is created in the AKS resource group.

### Additional Context

This is caused by the following in main.tf

```
resource "azurerm_network_security_group" "nsg" {
  count               = var.nsg_name == null ? 1 : 0
  name                = "${var.prefix}-nsg"
  location            = var.location
  resource_group_name = local.aks_rg.name
  tags                = var.tags
}

data "azurerm_network_security_group" "nsg" {
  count               = var.nsg_name == null ? 0 : 1
  name                = var.nsg_name
  resource_group_name = local.network_rg.name
}
```

Notice that when no nsg_name is supplied the resource_group_name is set to local.aks_rg.name, but when nsg_name is set it defaults to local.network_rg.name.

If you would like me to open a PR for this small change let me know.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riragh** [comment]
Internal ticket was created to investigate this further.

**Comment by riragh** [comment]
Upon investigating, found that the `network_rg` is the resource group that is user-defined and supplied to IAC via variable `vnet_resource_group_name`. The variable `vnet_resource_group_name` is used in BYO scenarios which would contain any pre-existing resources like vnet_name, subnet_names, nsg_name, or aks_uai_name. IAC scripts do not create this resource group.

The `network_rg` is just an internal variable which holds the information about the resource group provided via `vnet_resource_group_name`. See the code below which retrieves this information based of the provided `vnet_resource_group_name`: https://github.com/sassoftware/viya4-iac-azure/blob/main/main.tf#L36-L39

```
data "azurerm_resource_group" "network_rg" {
  count = var.vnet_resource_group_name == null ? 0 : 1
  name  = var.vnet_resource_group_name
}
```
This resource group information retrieved above is saved in the `network_rg` variable here: https://github.com/sassoftware/viya4-iac-azure/blob/main/main.tf#L36-L39 and used later for setting different values like nsg_name, subnets etc.
```
  network_rg = (var.vnet_resource_group_name == null
    ? local.aks_rg
    : data.azurerm_resource_group.network_rg[0]
  )
```
As IAC script doesn't create the network_rg, it cannot be used to create the NSG. The setup is correct as per design.
Please let me know if there is any question or concerns, if not I would like to close this issue.

**Comment by riragh** [comment]
Code was updated, all network related resources should get created into a vnet resource group if supplied by user. VNET gets created correctly in network resource group if vnet_resource_group_name is provided however, NSG creation was not following the same pattern. This PR corrects that behavior to follow the same logic.

If vnet_resource_group_name is provided without nsg_name, IAC will create NSG for you in the provided vnet resource group else NSG will created in the AKS resource group like before. See details in above linked PR. 
The updated code was merged to staging, will be released to main soon. Closing this issue.
