### ISSUE TITLE
Support for cloud-init (custom-data) on the compute nodepool

### ISSUE THREAD

**Issue by sasbxs** [sassoftware/viya4-iac-azure#333]
Given the recent emphasis on SAS Workload Management for compute, could we get a way to inject a cloud-init script into the compute nodepool/vmss?  I am using hostPath for SASWORK, and the mounted NvME drive does not have the appropriate permissions/ownership by default.  Currently (with a fixed number of nodes in my compute nodepool) I have to execute a script after the node is instantiated to make that NvMe drive appropriate for SASWORK -- which works fine. In an autoscaling situation (for SAS WLM) I need to have that happen dynamically as kubernetes adds new compute nodes on its own.  I've seen some JIRAs about maybe creating a daemonset to handle this, but those appear to have gone nowhere to me.  The solution that I have found is to use the az vmss update --custom-data ./myscript.sh command to add my NvME reconfiguration script to the instance start up.  It would be nice if I could inject that from the get-go (in the IAC project) rather than having to figure out how to set the nodes up properly after-the-fact.

**Comment by sayeun** [comment]
Opened internal ticket for PM review, PMCPFR-1534.

**Comment by sayeun** [comment]
Thank you for your suggestion.  Unfortunately, the feature request PMCPFR-1534 was rejected due to security concerns.  Closing this issue as we will not proceed further.
