### ISSUE TITLE
feat: (IAC-1009) Support CNI Overlay

### ISSUE THREAD

**Issue by runemy** [sassoftware/viya4-iac-azure#343]
Hi,

In current version of this IaC, the networking models Kubnet and Azure CNI is supported.
Microsoft do not recommend to use Kubnet in production environment and do not support Kubnet in new functionality like "Application gateway for containers". Azure CNI requires a lot of IPs (that cause ip exhaustion) and is not suited to connect with OnPrem (expressroute).

Since we need to connect our AKS, with viya-4, to OnPrem I would like to request support for "CNI Overlay"
- https://azure.microsoft.com/en-us/updates/azurecnioverlay/

```
  network_profile {
    network_plugin = "azure"
    network_plugin_mode = "overlay"
    ebpf_data_plane = "cilium"                                // Optional
    outbound_type = "userDefinedRouting"
  }
```

CNI Overlay exist in two versions 'Azure CNI Overlay' and 'Azure CNI Overlay Powered by Cilium'

**Comment by riragh** [comment]
@runemy, We had explored Azure CNI Overlay support early this year in May and it resulted in intermittent failures, networking and DNS issues. That led us to backlog the work around this. It's been a while that this feature is live, hoping it performs better now. This work is planned to be reinvestigated early next year.

**Comment by riragh** [comment]
Changes for Azure CNI Overlay have been released and available in the main branch.
