### ISSUE TITLE
feat: (IAC-1101) How to change the OS version of NFS Server/Jump Server

### ISSUE THREAD

**Issue by TakeshiMifune** [sassoftware/viya4-iac-azure#353]
Please tell me how to change the OS version of NFS Server/Jump Server.

https://github.com/sassoftware/viya4-iac-azure
I am referring to the above site.
It is assumed that a Viya environment will be constructed using the sample files under the "viya4-iac-azure/examples" folder.
(Specifically, it is assumed that "sample-input.tfvars" will be used.)

With the current default values, I think the NFS Server/Jump Server will be created with "ubuntu 20_04-lts", but I would like to create it with the OS version "22_04-lts".

I think it is possible to change the OS version by updating some configuration files.
If it is possible to change the OS version, could you please tell me which files need to be updated and where to update them?

Best Regards,
Takeshi Mifune

**Comment by riragh** [comment]
To update the VM OS version you would need to update the variable `os_offer` and `os_sku` in the variables.tf file here: `https://github.com/sassoftware/viya4-iac-azure/blob/main/modules/azurerm_vm/variables.tf`

The updated values should be:
```
variable "os_offer" {
  description = "Specifies the offer of the image used to create the virtual machines. Changing this forces a new resource to be created."
  type        = string
  default     = "0001-com-ubuntu-server-jammy"
}

variable "os_sku" {
  description = "Specifies the SKU of the image used to create the virtual machines. Changing this forces a new resource to be created."
  type        = string
  default     = "22_04-lts-gen2"
}
```

**Please Note:** The OMS agent VM extension is not support for Ubuntu 22.04, and hence even though the terraform apply command would be complete successfully you will see failure in Portal on the resource group deployment.
The OMS agent is in a deprecation path and will be retired on August 2024. The current recommendation from Microsoft is to migrate to the Azure Monitor Agent, which we are starting to explore.

**Comment by TakeshiMifune** [comment]
Hello riragh,

Thank you for your response.
I can close this issue.

Thanks and Regards,
Takeshi

**Comment by riragh** [comment]
Closing this issue based on above response.
