### ISSUE TITLE
Feature Request: Standard NFS server with raid 0 option

### ISSUE THREAD

**Issue by caili-zhang-sas** [sassoftware/viya4-iac-azure#369]
I found that Standard NFS was set to Raid 5 by default, with 4 disk attached to VM.
For Dev/Test environment, we want to use NFS server with only 1 disk, could you please add variable to modify disk number attached to NFS server?

**Comment by riragh** [comment]
Thank you for opening this feature enhancement request. This request will be reviewed and internal ticket will be created if request is approved. I'll post updates to this issue.

**Comment by riragh** [comment]
This request was reviewed internally. For any dev/test changes we recommend user to fork `viya4-iac-azure` repo and make the required changes for their testing.
In your case you would need to fork the repo and update the `data_disk_count` to 1 in `vms.tf` file. https://github.com/sassoftware/viya4-iac-azure/blob/main/vms.tf#L110
Closing this issue.
