### ISSUE TITLE
terraform plan returns Warning: Argument is deprecated - This property has been renamed to `authorized_ip_ranges` within the `api_server_access_profile` block 

### ISSUE THREAD

**Issue by spnmhb** [sassoftware/viya4-iac-azure#402]
### Terraform Version Details

Tried with both latest 1.9.7 and suggested in  https://github.com/sassoftware/viya4-iac-azure?tab=readme-ov-file#terraform-requirements 1.8.2   

azureuser@viya-spnmhb-jump-vm:~/deploy/viya4/viya4-iac-azure/files/tools$ ./iac_tooling_version.sh
{
  "terraform_version": "\"1.9.7\"",
  "terraform_revision": "null",
  "terraform_outdated": "false",
  "provider_selections": "{}"
}

azureuser@viya-spnmhb-jump-vm:~/deploy/viya4/viya4-iac-azure/files/tools$ ./iac_tooling_version.sh
{
  "terraform_version": "\"1.8.2\"",
  "terraform_revision": "null",
  "terraform_outdated": "true",
  "provider_selections": "{}"
}

### Terraform Variable File Details

[tf_files.zip](https://github.com/user-attachments/files/17307014/tf_files.zip)
tf_files.zip contains terraform.tfvars and the main.tf mentioned in the warning obtained (also outputs.tf and variables.tf in the same directory)

### Steps to Reproduce

- Create jumphost
- Install terraform, kubectl, jq, Azure Cli, Docker, helm, kustomize, git
- Clone the project 
   git clone https://github.com/sassoftware/viya4-iac-azure
- Create service principal
- Generate an SSH key pair that will be used in terraform.tfvars 
   ssh_public_key              = "~/.ssh/id_rsa.pub"
- create terraform.tfvars
- terraform init (also tried with terraform init -upgrade
- terraform plan 
  returns the following warning
╷
│ Warning: Argument is deprecated
│
│   with module.aks.azurerm_kubernetes_cluster.aks,
│   on modules/azure_aks/main.tf line 21, in resource "azurerm_kubernetes_cluster" "aks":
│   21:   api_server_authorized_ip_ranges = var.aks_cluster_endpoint_public_access_cidrs
│
│ This property has been renamed to `authorized_ip_ranges` within the `api_server_access_profile` block and will be removed in v4.0 of the provider
│
│ (and one more similar warning elsewhere)
╵

### Expected Behavior

Output with no warning or error messages

### Actual Behavior

- terraform plan 
  returns the following warning
╷
│ Warning: Argument is deprecated
│
│   with module.aks.azurerm_kubernetes_cluster.aks,
│   on modules/azure_aks/main.tf line 21, in resource "azurerm_kubernetes_cluster" "aks":
│   21:   api_server_authorized_ip_ranges = var.aks_cluster_endpoint_public_access_cidrs
│
│ This property has been renamed to `authorized_ip_ranges` within the `api_server_access_profile` block and will be removed in v4.0 of the provider
│
│ (and one more similar warning elsewhere)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riragh** [comment]
@spnmhb, this warning has been fixed in the major version of Terraform azurerm v4.0. We are consuming the new major version in the upcoming release. If you are interested please look at the PR #401.
If this answers your question I would like to close this issue.

**Comment by spnmhb** [comment]
Thanks for the answer @riragh, that makes sense. So at this moment, for trying to make the terraform plan command work, would it be enough to update azurerm to v4.0 and then re-run terraform init plan / terraform plan? In that case, how can I manage to upgrade azurerm?

**Comment by riragh** [comment]
@spnmhb, no just updating the azurerm version to v4.0 will not be enough. This was breaking change from the provider so we had to make sure we updated all the pieces in our code correctly to consume the breaking changes.
We have not released the changes but at the moment if you want to use the newer changes please pull "staging" branch and just run terraform plan.

**Comment by spnmhb** [comment]
@riragh Thank you very much for the answer. Just for information, is there an estimated date for the changes to be released?
