### ISSUE TITLE
changes needed to support azure network plugin

### ISSUE THREAD

**Issue by BarbaraWalters-sas** [sassoftware/viya4-iac-azure#43]
I needed the azure network plugin to install and use cilium which provides detailed performance details for communication. In modules/azure_aks/variables.tf I changed the variable "aks_network_plugin" default value to "azure".

I got an error that pod_cidr was incompatible with the azure plugin.
In the same directory, I modified main.tf and commented out the line that sets a value for pod_cidr

I got another error that said too few addresses were available in the subnet.
In the top level directory, I modified main.tf's value for aks_subnet_cidr_block to "192.168.16.0/20"

This last statement made many more ip addresses available than are necessary, but my Viya 4 deployment was successful after these changes.

I'm not recommending these settings in general, just documenting what worked for me.

**Comment by manoatsas** [comment]
Fixed in PR #78
