### ISSUE TITLE
Starting & stopping of jump-vm and nfs-vm blocks ssh access

### ISSUE THREAD

**Issue by varsovik** [sassoftware/viya4-iac-azure#55]
Hey,
Still needs to be confirm but I created twice the jump-vm and nfs-vm with the IaC TF templates.  Used my own private key.  After stopping and starting my jump-vm and nfs-vm I can't ssh anymore to the jump-vm.

```
ssh -i sbxfrv-viyadep-key jumpuser@52.247.125.242
ssh: connect to host 52.247.125.242 port 22: Connection refused
```

No change in inbound firewall rules or public IP address.  So port 22 is still open.  Only reason I can think of is something must be changed with public key in the nfs-vm?

Frederik.

**Comment by thpang** [comment]
@varsovik from the Azure portal can you try 'restarting' the jump vm. I found this did re-enable the sshd on the box. Just wondering what you might see if you try this.

**Comment by thpang** [comment]
If one stops the vm via the Azure portal, one must also restart the vm in order to have the sshd restart properly.
