### ISSUE TITLE
remove hardcoded passwords in samples

### ISSUE THREAD

**Issue by dwpage** [sassoftware/viya4-iac-azure#57]
https://github.com/sassoftware/viya4-iac-azure/blob/main/examples/sample-input-ppg.tfvars#L27
(and in a few other sample files)

Could we replace this with random_string or https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password

Or at least move the password into a comment, and leave the string as an obvious should be substituted value a la 
location = "<azure-location-value>" # e.g., "eastus2"

**Comment by thpang** [comment]
Closing this one. Found this affects subsequent runs of tf with these values being rotated.
