### ISSUE TITLE
Docker execution fails with multiple "data.external.iac_tooling_version is empty tuple" erros

### ISSUE THREAD

**Issue by cjguerrap** [sassoftware/viya4-iac-azure#62]
ubuntu@ip-10-249-6-127:~/sas/viya4-iac-azure$ docker run --rm   --env-file $HOME/sas/.azure_docker_creds.env   -v $HOME/sas/viya4-iac-azure:/workspace viya4-iac-azure   plan -var-file /workspace/terraform.tfvars -state /workspace/terraform.tfstate
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.template_file.nfs-cloudconfig: Refreshing state...
data.external.git_hash: Refreshing state...
data.template_cloudinit_config.nfs: Refreshing state...
data.azuread_service_principal.sp_client: Refreshing state...
data.azurerm_subscription.current: Refreshing state...

------------------------------------------------------------------------

Warning: Interpolation-only expressions are deprecated

  on main.tf line 134, in module "vnet":
 134:     "${local.aks_subnet_name}"  = ["Microsoft.Sql"],

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and one more similar warning elsewhere)

Error: Invalid index

  on main.tf line 396, in data "template_file" "sas_iac_buildinfo":
 396:     terraform-version     = lookup(data.external.iac_tooling_version.0.result, "terraform_version")
    |----------------
    | data.external.iac_tooling_version is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on main.tf line 397, in data "template_file" "sas_iac_buildinfo":
 397:     provider-selections   = lookup(data.external.iac_tooling_version.0.result, "provider_selections")
    |----------------
    | data.external.iac_tooling_version is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on main.tf line 398, in data "template_file" "sas_iac_buildinfo":
 398:     terraform-revision    = lookup(data.external.iac_tooling_version.0.result, "terraform_revision")
    |----------------
    | data.external.iac_tooling_version is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on main.tf line 399, in data "template_file" "sas_iac_buildinfo":
 399:     terraform-outdated    = lookup(data.external.iac_tooling_version.0.result, "terraform_outdated")
    |----------------
    | data.external.iac_tooling_version is empty tuple

The given key does not identify an element in this collection value.

**Comment by thpang** [comment]
@cjguerrap when you ran this did you have old tfstate files? If you could try this again when you are able to remove your tfstate files to verify. NOTE: If you still have infrastructure setup in Azure you can delete the top level resource group from within the UI and then safely remove the tfstate files.

**Comment by cjguerrap** [comment]
Thomas,

It fails with the same displayed error even after deleting the tfstate files.
I am running this from inside an Azure VM with:
CentOS Linux release 7.7.1908 (Core)
Docker version 19.03.8, build afacb8b

**Comment by thpang** [comment]
@cjguerrap and @erwangranger I found the issue.

Changes to the iac_tooling_version.sh file and logic in the data.external.iac_tooling_version were not in sync. I removed the guard around the creation of the data element as the script now successfully works with both docker / terraform.

I'll be creating a pr for this one and attaching this issue.

Testing fix this evening.
