### ISSUE TITLE
Documentation: Remove bracekts and replace with quotation marks in ENV files

### ISSUE THREAD

**Issue by holdeneoneal** [sassoftware/viya4-iac-azure#74]
The environment variable notation usage of brackets in https://github.com/sassoftware/viya4-iac-azure#docker-1 is slightly misleading. The use of brackets around the value will yield error messages when attempting to run the commands later. The Docker section should be updated to match the notation used in the Terraform section next to it.

Environment variable notation in the below linked sections should also be updated to use quotes instead of brackets:
https://github.com/sassoftware/viya4-iac-azure/blob/main/docs/user/TerraformAzureAuthentication.md#terraform
https://github.com/sassoftware/viya4-iac-azure/blob/main/docs/user/TerraformAzureAuthentication.md#docker

**Comment by enderm** [comment]
I'm working on a change that touches all these areas anway

**Comment by enderm** [comment]
fixed via https://github.com/sassoftware/viya4-iac-azure/pull/76
