### ISSUE TITLE
Support max_pods in node pools

### ISSUE THREAD

**Issue by NormJohnIV** [sassoftware/viya4-iac-azure#75]
Add support to the node-pools for setting max pod count.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool

**Comment by thpang** [comment]
Adding in docs on reason we need to be able to set `max_pods` for dynamic node pools.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#azure-kubernetes-service-limits

**Comment by manoatsas** [comment]
Related to #43

**Comment by manoatsas** [comment]
Fixed in #78
