### ISSUE TITLE
Expose NFS/Jumpbox machine_type

### ISSUE THREAD

**Issue by NormJohnIV** [sassoftware/viya4-iac-azure#81]
In order to change the instance type for the nfs and jumpbox, variables need to be exposed.

**Comment by andybouts** [comment]
Suggest default for NFS VM is D8s_v4
Suggest default for Bastion / Jump VM is B2s

**Comment by thpang** [comment]
@manoatsas if you can compare what we currently use for our NFS `Standard_E8_v3` vs the suggestion of `Standard_D8s_v4`. The same would hold true in comparing the current default for the Jump server `Standard_E8_v3` vs the suggestion of `Standard_B2s`. Thx.
