### ISSUE TITLE
apply tags to netapp objects

### ISSUE THREAD

**Issue by enderm** [sassoftware/viya4-iac-azure#85]
The objects in the netapp module need to have the tags from the user "tags" variable applied to them.
On some sites, the IT department tags created resources with default tags that indicate who created the resource. That leads to the terraform state to get out of sync with the resources. So, on re-apply, the externally added tags show up as diffs. 
Pre-emptively applying those tags avoids that issue.
A side-effect of the netapp resources changing their state is that the jump host gets recreated. Adding the correct tags here avoids that issue.

**Comment by manoatsas** [comment]
Fixed in the commit.
