### ISSUE TITLE
Docker container error: failed to execute "git": fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by AMenrath** [sassoftware/viya4-iac-azure#96]
I am trying to use the docker container. I was able to build it and run a terraform plan or apply inside the container.
However the container session ends with this error:

data.external.iac_tooling_version: Refreshing state...
data.external.git_hash: Refreshing state...
data.template_file.nfs-cloudconfig: Refreshing state...
data.template_cloudinit_config.nfs: Refreshing state...
data.azurerm_subscription.current: Refreshing state...
**Error: failed to execute "git": fatal: not a git repository (or any of the parent directories): .git**

Any ideas how to fix the error?

**Comment by thpang** [comment]
You're creating a docker image from the submodule you've pulled from our internal Gitlab repo. You should be building the image from that location, or if you are only interested in using the GitHub repo, you'll need to clone this one directly and then build the docker image.
